// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { INpgsqlSingletonOptions, NpgsqlOptionsExtension } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal/internal/index.js";
import type { INpgsqlDataSourceConfigurationPlugin } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure/internal/index.js";
import type { NpgsqlEStringTypeMapping } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Mapping/internal/index.js";
import type { NpgsqlConnection, NpgsqlDataSource } from "../../Npgsql/internal/index.js";
import type { ConcurrentDictionary_2 } from "@tsonic/dotnet/System.Collections.Concurrent/internal/index.js";
import type { IEnumerable_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { DbConnection, DbDataSource } from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import type { StringBuilder } from "@tsonic/dotnet/System.Text/internal/index.js";
import type { Task, Task_1, ValueTask, ValueTask_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import type { Transaction } from "@tsonic/dotnet/System.Transactions/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Exception, Func_3, Func_4, IAsyncDisposable, IDisposable, Int32, IServiceProvider, Nullable_1, Object as ClrObject, String as ClrString, TimeSpan, Type, Void } from "@tsonic/dotnet/System/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IDbContextOptions, IResettableService } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IModel, IProperty } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Storage_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { CoreTypeMapping, ExecutionResult_1, ExecutionStrategyDependencies, IDatabaseCreator, IDbContextTransactionManager, IExecutionStrategy, IExecutionStrategyFactory, IRawSqlCommandBuilder, IRelationalConnection, IRelationalDatabaseCreator, IRelationalTransactionManager, IRelationalTypeMappingSource, ISqlGenerationHelper, ITransactionEnlistmentManager, ITypeMappingSource, RelationalConnection, RelationalConnectionDependencies, RelationalDatabaseCreator, RelationalDatabaseCreatorDependencies, RelationalExecutionStrategyFactory, RelationalSqlGenerationHelper, RelationalSqlGenerationHelperDependencies, RelationalTypeMapping, RelationalTypeMappingInfo, RelationalTypeMappingSource, RelationalTypeMappingSourceDependencies, TypeMappingSourceDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { DbContext } from "@tsonic/efcore/Microsoft.EntityFrameworkCore/internal/index.js";

export interface INpgsqlRelationalConnection$instance extends IRelationalConnection, IRelationalTransactionManager, IDbContextTransactionManager, IResettableService, IDisposable, IAsyncDisposable {
    readonly __tsonic_iface_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_INpgsqlRelationalConnection: never;

    readonly DataSource: DbDataSource | undefined;
    CloneWith(connectionString: string, async: boolean, cancellationToken?: CancellationToken): ValueTask_1<INpgsqlRelationalConnection>;
    CreateAdminConnection(): INpgsqlRelationalConnection;
}


export interface INpgsqlRelationalConnection$instance extends Microsoft_EntityFrameworkCore_Infrastructure_Internal.IResettableService, Microsoft_EntityFrameworkCore_Storage_Internal.IDbContextTransactionManager, Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalConnection, Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalTransactionManager, System_Internal.IAsyncDisposable, System_Internal.IDisposable {}

export type INpgsqlRelationalConnection = INpgsqlRelationalConnection$instance;

export interface NpgsqlDatabaseCreator$instance extends RelationalDatabaseCreator {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_NpgsqlDatabaseCreator: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IDatabaseCreator: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalDatabaseCreator: never;

    RetryDelay: TimeSpan;
    RetryTimeout: TimeSpan;
    Create(): void;
    CreateAsync(cancellationToken?: CancellationToken): Task;
    CreateTables(): void;
    CreateTablesAsync(cancellationToken?: CancellationToken): Task;
    Delete(): void;
    DeleteAsync(cancellationToken?: CancellationToken): Task;
    Exists(): boolean;
    ExistsAsync(cancellationToken?: CancellationToken): Task_1<System_Internal.Boolean>;
    HasTables(): boolean;
    HasTablesAsync(cancellationToken?: CancellationToken): Task_1<System_Internal.Boolean>;
}


export const NpgsqlDatabaseCreator: {
    new(dependencies: RelationalDatabaseCreatorDependencies, connection: INpgsqlRelationalConnection, rawSqlCommandBuilder: IRawSqlCommandBuilder): NpgsqlDatabaseCreator;
};


export type NpgsqlDatabaseCreator = NpgsqlDatabaseCreator$instance;

export interface NpgsqlDataSourceManager$instance {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_NpgsqlDataSourceManager: never;

    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    CreateDataSource(npgsqlOptionsExtension: NpgsqlOptionsExtension): NpgsqlDataSource;
    Dispose(): void;
    DisposeAsync(): ValueTask;
    GetDataSource(npgsqlOptionsExtension: NpgsqlOptionsExtension, applicationServiceProvider: IServiceProvider): DbDataSource | undefined;
}


export const NpgsqlDataSourceManager: {
    new(plugins: IEnumerable_1<INpgsqlDataSourceConfigurationPlugin>): NpgsqlDataSourceManager;
};


export type NpgsqlDataSourceManager = NpgsqlDataSourceManager$instance;

export interface NpgsqlExecutionStrategy$instance {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_NpgsqlExecutionStrategy: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IExecutionStrategy: never;

    readonly RetriesOnFailure: boolean;
    Execute<TState, TResult>(state: TState, operation: Func_3<DbContext, TState, TResult>, verifySucceeded: Func_3<DbContext, TState, ExecutionResult_1<TResult>>): TResult;
    ExecuteAsync<TState, TResult>(state: TState, operation: Func_4<DbContext, TState, CancellationToken, Task_1<TResult>>, verifySucceeded: Func_4<DbContext, TState, CancellationToken, Task_1<ExecutionResult_1<TResult>>>, cancellationToken: CancellationToken): Task_1<TResult>;
}


export const NpgsqlExecutionStrategy: {
    new(dependencies: ExecutionStrategyDependencies): NpgsqlExecutionStrategy;
};


export type NpgsqlExecutionStrategy = NpgsqlExecutionStrategy$instance;

export interface NpgsqlExecutionStrategyFactory$instance extends RelationalExecutionStrategyFactory {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_NpgsqlExecutionStrategyFactory: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IExecutionStrategyFactory: never;

    CreateDefaultStrategy(dependencies: ExecutionStrategyDependencies): IExecutionStrategy;
}


export const NpgsqlExecutionStrategyFactory: {
    new(dependencies: ExecutionStrategyDependencies): NpgsqlExecutionStrategyFactory;
};


export type NpgsqlExecutionStrategyFactory = NpgsqlExecutionStrategyFactory$instance;

export interface NpgsqlRelationalConnection$instance extends RelationalConnection, Microsoft_EntityFrameworkCore_Storage_Internal.ITransactionEnlistmentManager {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_NpgsqlRelationalConnection: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IResettableService: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IDbContextTransactionManager: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalConnection: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalTransactionManager: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_ITransactionEnlistmentManager: never;
    readonly __tsonic_iface_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_INpgsqlRelationalConnection: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    get ConnectionString(): string | undefined;
    set ConnectionString(value: string | undefined);
    readonly CurrentAmbientTransaction: Transaction | undefined;
    get DataSource(): DbDataSource | undefined;
    set DataSource(value: DbDataSource | undefined);
    DbConnection: NpgsqlConnection;
    get DbDataSource(): DbDataSource | undefined;
    set DbDataSource(value: DbDataSource | undefined);
    readonly SupportsAmbientTransactions: boolean;
    CloneWith(connectionString: string, async: boolean, cancellationToken?: CancellationToken): ValueTask_1<INpgsqlRelationalConnection>;
    CreateAdminConnection(): INpgsqlRelationalConnection;
    CreateDbConnection(): DbConnection;
}


export const NpgsqlRelationalConnection: {
    new(dependencies: RelationalConnectionDependencies, dataSourceManager: NpgsqlDataSourceManager, options: IDbContextOptions): NpgsqlRelationalConnection;
};


export interface __NpgsqlRelationalConnection$views {
    As_INpgsqlRelationalConnection(): INpgsqlRelationalConnection$instance;
}

export type NpgsqlRelationalConnection = NpgsqlRelationalConnection$instance & __NpgsqlRelationalConnection$views;


export interface NpgsqlSqlGenerationHelper$instance extends RelationalSqlGenerationHelper {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_NpgsqlSqlGenerationHelper: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_ISqlGenerationHelper: never;

    DelimitIdentifier(identifier: string): string;
    DelimitIdentifier(builder: StringBuilder, identifier: string): void;
}


export const NpgsqlSqlGenerationHelper: {
    new(dependencies: RelationalSqlGenerationHelperDependencies): NpgsqlSqlGenerationHelper;
};


export type NpgsqlSqlGenerationHelper = NpgsqlSqlGenerationHelper$instance;

export interface NpgsqlTransientExceptionDetector$instance {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_NpgsqlTransientExceptionDetector: never;

}


export const NpgsqlTransientExceptionDetector: {
    new(): NpgsqlTransientExceptionDetector;
    ShouldRetryOn(ex: Exception): boolean;
};


export type NpgsqlTransientExceptionDetector = NpgsqlTransientExceptionDetector$instance;

export interface NpgsqlTypeMappingSource$instance extends RelationalTypeMappingSource {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Storage_Internal_NpgsqlTypeMappingSource: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalTypeMappingSource: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_ITypeMappingSource: never;

    readonly EStringTypeMapping: NpgsqlEStringTypeMapping;
    readonly ClrTypeMappings: ConcurrentDictionary_2<Type, RelationalTypeMapping>;
    readonly StoreTypeMappings: ConcurrentDictionary_2<System_Internal.String, RelationalTypeMapping[]>;
    FindBaseMapping(mappingInfo: RelationalTypeMappingInfo): RelationalTypeMapping | undefined;
    FindCollectionMapping(info: RelationalTypeMappingInfo, modelType: Type, providerType: Type, elementMapping: CoreTypeMapping): RelationalTypeMapping | undefined;
    FindCollectionMapping(storeType: string, modelClrType: Type, providerClrType: Type, elementMapping: CoreTypeMapping): RelationalTypeMapping | undefined;
    FindContainerMapping(containerClrType: Type, containeeTypeMapping: RelationalTypeMapping, model: IModel): RelationalTypeMapping | undefined;
    FindEnumMapping(mappingInfo: RelationalTypeMappingInfo): RelationalTypeMapping | undefined;
    FindMapping(mappingInfo: RelationalTypeMappingInfo): RelationalTypeMapping | undefined;
    FindMapping(property: IProperty): RelationalTypeMapping | undefined;
    FindRowValueMapping(mappingInfo: RelationalTypeMappingInfo): RelationalTypeMapping | undefined;
    FindUserRangeMapping(mappingInfo: RelationalTypeMappingInfo): RelationalTypeMapping | undefined;
    ParseStoreTypeName(storeTypeName: string, unicode: Nullable_1<System_Internal.Boolean>, size: Nullable_1<System_Internal.Int32>, precision: Nullable_1<System_Internal.Int32>, scale: Nullable_1<System_Internal.Int32>): string | undefined;
}


export const NpgsqlTypeMappingSource: {
    new(dependencies: TypeMappingSourceDependencies, relationalDependencies: RelationalTypeMappingSourceDependencies, sqlGenerationHelper: ISqlGenerationHelper, options: INpgsqlSingletonOptions): NpgsqlTypeMappingSource;
};


export type NpgsqlTypeMappingSource = NpgsqlTypeMappingSource$instance;

