// Generated by tsbindgen - Architecture
// Namespace: Npgsql.Util
// Module Stub - Do Not Execute

throw new Error(
  'Cannot import CLR namespace Npgsql.Util in JavaScript runtime. ' +
  'This module provides TypeScript type definitions only. ' +
  'Actual implementation requires .NET runtime via Tsonic compiler.'
);
