// Generated by tsbindgen - Architecture
// Namespace: Npgsql.Util
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Npgsql.Util/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { ValueType } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { NpgsqlTimeout as NpgsqlTimeout } from './Npgsql.Util/internal/index.js';
