// Generated by tsbindgen - Architecture
// Namespace: Npgsql.BackendMessages
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Npgsql.BackendMessages/internal/index.js';

// Cross-namespace type imports for constraints
import type { Int16, Int32, Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { FieldDescription as FieldDescription } from './Npgsql.BackendMessages/internal/index.js';
