// Generated by tsbindgen - Architecture
// Namespace: Npgsql.Replication.PgOutput
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Npgsql.Replication.PgOutput/internal/index.js';

// Cross-namespace type imports for constraints
import type { PostgresType } from './Npgsql.PostgresTypes/internal/index.js';
import type { LogicalReplicationSlot } from './Npgsql.Replication.Internal/internal/index.js';
import type { ReplicationSlotOptions } from './Npgsql.Replication/internal/index.js';
import type { NpgsqlLogSequenceNumber } from './NpgsqlTypes/internal/index.js';
import type { IAsyncEnumerable, IAsyncEnumerator, IEnumerable, List } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Stream, TextReader } from '@tsonic/dotnet/System.IO.js';
import type { Boolean as ClrBoolean, Byte, Enum, IComparable, IConvertible, IEquatable, IFormattable, Int32, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString, Type, UInt16, UInt64 } from '@tsonic/dotnet/System.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { PgOutputProtocolVersion as PgOutputProtocolVersion } from './Npgsql.Replication.PgOutput/internal/index.js';
export { PgOutputReplicationOptions as PgOutputReplicationOptions } from './Npgsql.Replication.PgOutput/internal/index.js';
export { PgOutputReplicationSlot as PgOutputReplicationSlot } from './Npgsql.Replication.PgOutput/internal/index.js';
export { PgOutputStreamingMode as PgOutputStreamingMode } from './Npgsql.Replication.PgOutput/internal/index.js';
export { ReplicationTuple as ReplicationTuple } from './Npgsql.Replication.PgOutput/internal/index.js';
export { ReplicationValue as ReplicationValue } from './Npgsql.Replication.PgOutput/internal/index.js';
export { TupleDataKind as TupleDataKind } from './Npgsql.Replication.PgOutput/internal/index.js';
