// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.Internal/internal/index.js';

// Cross-namespace type imports for constraints
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Boolean as ClrBoolean, IEquatable, Int32, Int64, Nullable, Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';
import type { IAnnotation, IReadOnlyAnnotatable } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js';
import type { IColumn, IRelationalAnnotationProvider, IRelationalModel, ITable, ITableIndex, RelationalAnnotationProvider, RelationalAnnotationProviderDependencies } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CockroachDbAnnotationNames$instance as CockroachDbAnnotationNames } from './Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.Internal/internal/index.js';
export { IdentitySequenceOptionsData as IdentitySequenceOptionsData } from './Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.Internal/internal/index.js';
export { NpgsqlAnnotationNames$instance as NpgsqlAnnotationNames } from './Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.Internal/internal/index.js';
export { NpgsqlAnnotationProvider as NpgsqlAnnotationProvider } from './Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.Internal/internal/index.js';
