// Generated by tsbindgen - Architecture
// Namespace: Npgsql.Schema
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Npgsql.Schema/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { PostgresType } from './Npgsql.PostgresTypes/internal/index.js';
import type { NpgsqlDbType } from './NpgsqlTypes/internal/index.js';
import type { DbColumn } from '@tsonic/dotnet/System.Data.Common.js';
import type { Boolean as ClrBoolean, Int16, Int32, Nullable, Object as ClrObject, String as ClrString, Type, UInt32 } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { NpgsqlDbColumn as NpgsqlDbColumn } from './Npgsql.Schema/internal/index.js';
