// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Json
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Json/internal/index.js';

// Cross-namespace type imports for constraints
import type { BitArray } from '@tsonic/dotnet/System.Collections.js';
import type { Object as ClrObject, Void } from '@tsonic/dotnet/System.js';
import type { Expression } from '@tsonic/dotnet/System.Linq.Expressions.js';
import type { PhysicalAddress } from '@tsonic/dotnet/System.Net.NetworkInformation.js';
import type { Utf8JsonWriter } from '@tsonic/dotnet/System.Text.Json.js';
import type { JsonValueReaderWriter, Utf8JsonReaderManager } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.Json.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { JsonBitArrayReaderWriter as JsonBitArrayReaderWriter } from './Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Json/internal/index.js';
export { JsonMacaddrReaderWriter as JsonMacaddrReaderWriter } from './Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.Json/internal/index.js';
