// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { ICollection } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { Int32, String as ClrString, TimeSpan } from "@tsonic/dotnet/System.js";
import type { DbContext } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import * as Microsoft_EntityFrameworkCore_Storage_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";
import type { ExecutionStrategy, ExecutionStrategyDependencies, IExecutionStrategy } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export interface NpgsqlRetryingExecutionStrategy$instance extends ExecutionStrategy {
}


export const NpgsqlRetryingExecutionStrategy: {
    new(context: DbContext): NpgsqlRetryingExecutionStrategy;
    new(dependencies: ExecutionStrategyDependencies): NpgsqlRetryingExecutionStrategy;
    new(context: DbContext, maxRetryCount: int): NpgsqlRetryingExecutionStrategy;
    new(dependencies: ExecutionStrategyDependencies, maxRetryCount: int): NpgsqlRetryingExecutionStrategy;
    new(dependencies: ExecutionStrategyDependencies, errorCodesToAdd: ICollection<System_Internal.String>): NpgsqlRetryingExecutionStrategy;
    new(context: DbContext, maxRetryCount: int, maxRetryDelay: TimeSpan, errorCodesToAdd: ICollection<System_Internal.String>): NpgsqlRetryingExecutionStrategy;
    new(dependencies: ExecutionStrategyDependencies, maxRetryCount: int, maxRetryDelay: TimeSpan, errorCodesToAdd: ICollection<System_Internal.String>): NpgsqlRetryingExecutionStrategy;
};


export type NpgsqlRetryingExecutionStrategy = NpgsqlRetryingExecutionStrategy$instance;

