// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Operations
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { String as ClrString } from "@tsonic/dotnet/System.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { IAnnotatable, IReadOnlyAnnotatable } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import * as Microsoft_EntityFrameworkCore_Metadata_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import type { IMutableAnnotatable } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import * as Microsoft_EntityFrameworkCore_Migrations_Operations_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.Operations.js";
import type { DatabaseOperation, MigrationOperation } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.Operations.js";

export interface NpgsqlCreateDatabaseOperation$instance extends DatabaseOperation {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IAnnotatable: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IReadOnlyAnnotatable: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Metadata_IMutableAnnotatable: never;

    Name: string;
    get Tablespace(): string | undefined;
    set Tablespace(value: string | undefined);
    get Template(): string | undefined;
    set Template(value: string | undefined);
}


export const NpgsqlCreateDatabaseOperation: {
    new(): NpgsqlCreateDatabaseOperation;
};


export type NpgsqlCreateDatabaseOperation = NpgsqlCreateDatabaseOperation$instance;

export interface NpgsqlDropDatabaseOperation$instance extends MigrationOperation {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IAnnotatable: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IReadOnlyAnnotatable: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Metadata_IMutableAnnotatable: never;

    Name: string;
}


export const NpgsqlDropDatabaseOperation: {
    new(): NpgsqlDropDatabaseOperation;
};


export type NpgsqlDropDatabaseOperation = NpgsqlDropDatabaseOperation$instance;

