// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Query.Expressions.Internal
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { PgExpressionType } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Query.Expressions/internal/index.js";
import type { IEnumerable_1, IReadOnlyList_1, ISet_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Linq_Expressions_Internal from "@tsonic/dotnet/System.Linq.Expressions/internal/index.js";
import type { Expression, ExpressionType, ExpressionVisitor } from "@tsonic/dotnet/System.Linq.Expressions/internal/index.js";
import type { RegexOptions } from "@tsonic/dotnet/System.Text.RegularExpressions/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Enum, IComparable, IConvertible, IEquatable_1, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Query_SqlExpressions_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.SqlExpressions/internal/index.js";
import type { ITableBasedExpression, OrderingExpression, SqlExpression, SqlFunctionExpression, TableExpression, TableExpressionBase, TableValuedFunctionExpression } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.SqlExpressions/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Query_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query/internal/index.js";
import type { ExpressionPrinter, IPrintableExpression, IRelationalQuotableExpression } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query/internal/index.js";
import type { RelationalTypeMapping } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage/internal/index.js";

export enum PgAllOperatorType {
    Like = 0,
    ILike = 1
}


export enum PgAnyOperatorType {
    Equal = 0,
    Like = 1,
    ILike = 2
}


export interface PgTableValuedFunctionExpression_ColumnInfo$instance {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgTableValuedFunctionExpression_ColumnInfo: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    Name: string;
    get TypeMapping(): RelationalTypeMapping | undefined;
    set TypeMapping(value: RelationalTypeMapping | undefined);
    Deconstruct(Name: string, TypeMapping: RelationalTypeMapping): void;
    Equals(obj: unknown): boolean;
    Equals(other: PgTableValuedFunctionExpression_ColumnInfo): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const PgTableValuedFunctionExpression_ColumnInfo: {
    new(Name: string, TypeMapping: RelationalTypeMapping): PgTableValuedFunctionExpression_ColumnInfo;
};


export type PgTableValuedFunctionExpression_ColumnInfo = PgTableValuedFunctionExpression_ColumnInfo$instance;

export interface PgAllExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgAllExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Array: SqlExpression;
    readonly Item: SqlExpression;
    readonly OperatorType: PgAllOperatorType;
    readonly Type: Type;
    Equals(obj: unknown): boolean;
    Equals(other: PgAllExpression): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    ToString(): string;
    Update(item: SqlExpression, array: SqlExpression): PgAllExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgAllExpression: {
    new(item: SqlExpression, array: SqlExpression, operatorType: PgAllOperatorType, typeMapping: RelationalTypeMapping): PgAllExpression;
};


export type PgAllExpression = PgAllExpression$instance;

export interface PgAnyExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgAnyExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Array: SqlExpression;
    readonly Item: SqlExpression;
    readonly OperatorType: PgAnyOperatorType;
    readonly Type: Type;
    Equals(obj: unknown): boolean;
    Equals(other: PgAnyExpression): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    ToString(): string;
    Update(item: SqlExpression, array: SqlExpression): PgAnyExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgAnyExpression: {
    new(item: SqlExpression, array: SqlExpression, operatorType: PgAnyOperatorType, typeMapping: RelationalTypeMapping): PgAnyExpression;
};


export type PgAnyExpression = PgAnyExpression$instance;

export interface PgArrayIndexExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgArrayIndexExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Array: SqlExpression;
    readonly Index: SqlExpression;
    readonly IsNullable: boolean;
    Equals(other: PgArrayIndexExpression): boolean;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    ToString(): string;
    Update(array: SqlExpression, index: SqlExpression): PgArrayIndexExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgArrayIndexExpression: {
    new(array: SqlExpression, index: SqlExpression, nullable: boolean, type: Type, typeMapping: RelationalTypeMapping): PgArrayIndexExpression;
};


export type PgArrayIndexExpression = PgArrayIndexExpression$instance;

export interface PgArraySliceExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgArraySliceExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Array: SqlExpression;
    readonly IsNullable: boolean;
    readonly LowerBound: SqlExpression | undefined;
    readonly UpperBound: SqlExpression | undefined;
    Equals(other: PgArraySliceExpression): boolean;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    ToString(): string;
    Update(array: SqlExpression, lowerBound: SqlExpression, upperBound: SqlExpression): PgArraySliceExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgArraySliceExpression: {
    new(array: SqlExpression, lowerBound: SqlExpression, upperBound: SqlExpression, nullable: boolean, type: Type, typeMapping: RelationalTypeMapping): PgArraySliceExpression;
};


export type PgArraySliceExpression = PgArraySliceExpression$instance;

export interface PgBinaryExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgBinaryExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;

    readonly Left: SqlExpression;
    readonly OperatorType: PgExpressionType;
    readonly Right: SqlExpression;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    Update(left: SqlExpression, right: SqlExpression): PgBinaryExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgBinaryExpression: {
    new(operatorType: PgExpressionType, left: SqlExpression, right: SqlExpression, type: Type, typeMapping: RelationalTypeMapping): PgBinaryExpression;
};


export type PgBinaryExpression = PgBinaryExpression$instance;

export interface PgDeleteExpression$instance extends Expression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgDeleteExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;

    readonly FromItems: IReadOnlyList_1<TableExpressionBase>;
    readonly NodeType: ExpressionType;
    readonly Predicate: SqlExpression | undefined;
    readonly Table: TableExpression;
    readonly Tags: ISet_1<System_Internal.String>;
    readonly Type: Type;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Update(predicate: SqlExpression): PgDeleteExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgDeleteExpression: {
    new(table: TableExpression, fromItems: IReadOnlyList_1<TableExpressionBase>, predicate: SqlExpression, tags: ISet_1<System_Internal.String>): PgDeleteExpression;
};


export type PgDeleteExpression = PgDeleteExpression$instance;

export interface PgFunctionExpression$instance extends SqlFunctionExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgFunctionExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly AggregateOrderings: IReadOnlyList_1<OrderingExpression>;
    readonly AggregatePredicate: SqlExpression | undefined;
    readonly ArgumentNames: IReadOnlyList_1<string | undefined>;
    readonly Arguments: IReadOnlyList_1<SqlExpression>;
    readonly ArgumentSeparators: IReadOnlyList_1<string | undefined>;
    readonly ArgumentsPropagateNullability: IReadOnlyList_1<System_Internal.Boolean>;
    readonly IsAggregateDistinct: boolean;
    ApplyTypeMapping(typeMapping: RelationalTypeMapping): SqlFunctionExpression;
    Equals(obj: unknown): boolean;
    Equals(other: PgFunctionExpression): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Update(instance: SqlExpression, arguments: IReadOnlyList_1<SqlExpression>): SqlFunctionExpression;
    UpdateAggregateComponents(predicate: SqlExpression, orderings: IReadOnlyList_1<OrderingExpression>): PgFunctionExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgFunctionExpression: {
    new(name: string, arguments: IEnumerable_1<SqlExpression>, argumentNames: IEnumerable_1<System_Internal.String>, argumentSeparators: IEnumerable_1<System_Internal.String>, aggregateDistinct: boolean, aggregatePredicate: SqlExpression, aggregateOrderings: IReadOnlyList_1<OrderingExpression>, nullable: boolean, argumentsPropagateNullability: IEnumerable_1<System_Internal.Boolean>, type: Type, typeMapping: RelationalTypeMapping): PgFunctionExpression;
    CreateWithArgumentSeparators(name: string, arguments: IEnumerable_1<SqlExpression>, argumentSeparators: IEnumerable_1<System_Internal.String>, nullable: boolean, argumentsPropagateNullability: IEnumerable_1<System_Internal.Boolean>, builtIn: boolean, type: Type, typeMapping: RelationalTypeMapping): PgFunctionExpression;
    CreateWithNamedArguments(name: string, arguments: IEnumerable_1<SqlExpression>, argumentNames: IEnumerable_1<System_Internal.String>, nullable: boolean, argumentsPropagateNullability: IEnumerable_1<System_Internal.Boolean>, builtIn: boolean, type: Type, typeMapping: RelationalTypeMapping): PgFunctionExpression;
};


export type PgFunctionExpression = PgFunctionExpression$instance;

export interface PgILikeExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgILikeExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly EscapeChar: SqlExpression | undefined;
    readonly Match: SqlExpression;
    readonly Pattern: SqlExpression;
    Equals(obj: unknown): boolean;
    Equals(other: PgILikeExpression): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    ToString(): string;
    Update(match: SqlExpression, pattern: SqlExpression, escapeChar: SqlExpression): PgILikeExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgILikeExpression: {
    new(match: SqlExpression, pattern: SqlExpression, escapeChar: SqlExpression, typeMapping: RelationalTypeMapping): PgILikeExpression;
};


export type PgILikeExpression = PgILikeExpression$instance;

export interface PgJsonTraversalExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgJsonTraversalExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Expression: SqlExpression;
    readonly Path: IReadOnlyList_1<SqlExpression>;
    readonly ReturnsText: boolean;
    Append(pathComponent: SqlExpression): PgJsonTraversalExpression;
    Equals(obj: unknown): boolean;
    Equals(other: PgJsonTraversalExpression): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    ToString(): string;
    Update(expression: SqlExpression, path: IReadOnlyList_1<SqlExpression>): PgJsonTraversalExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgJsonTraversalExpression: {
    new(expression: SqlExpression, path: IReadOnlyList_1<SqlExpression>, returnsText: boolean, type: Type, typeMapping: RelationalTypeMapping): PgJsonTraversalExpression;
};


export type PgJsonTraversalExpression = PgJsonTraversalExpression$instance;

export interface PgNewArrayExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgNewArrayExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;

    readonly Expressions: IReadOnlyList_1<SqlExpression>;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    Update(expressions: IReadOnlyList_1<SqlExpression>): PgNewArrayExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgNewArrayExpression: {
    new(expressions: IReadOnlyList_1<SqlExpression>, type: Type, typeMapping: RelationalTypeMapping): PgNewArrayExpression;
};


export type PgNewArrayExpression = PgNewArrayExpression$instance;

export interface PgRegexMatchExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgRegexMatchExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Match: SqlExpression;
    readonly Options: RegexOptions;
    readonly Pattern: SqlExpression;
    readonly Type: Type;
    Equals(other: PgRegexMatchExpression): boolean;
    Equals(other: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    ToString(): string;
    Update(match: SqlExpression, pattern: SqlExpression): PgRegexMatchExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgRegexMatchExpression: {
    new(match: SqlExpression, pattern: SqlExpression, options: RegexOptions, typeMapping: RelationalTypeMapping): PgRegexMatchExpression;
};


export type PgRegexMatchExpression = PgRegexMatchExpression$instance;

export interface PgRowValueExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgRowValueExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Values: IReadOnlyList_1<SqlExpression>;
    Equals(obj: unknown): boolean;
    Equals(other: PgRowValueExpression): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    Update(values: IReadOnlyList_1<SqlExpression>): PgRowValueExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgRowValueExpression: {
    new(values: IReadOnlyList_1<SqlExpression>, type: Type, typeMapping: RelationalTypeMapping): PgRowValueExpression;
};


export type PgRowValueExpression = PgRowValueExpression$instance;

export interface PgTableValuedFunctionExpression$instance extends TableValuedFunctionExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgTableValuedFunctionExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_SqlExpressions_ITableBasedExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly ColumnInfos: IReadOnlyList_1<PgTableValuedFunctionExpression_ColumnInfo> | undefined;
    readonly WithOrdinality: boolean;
    Clone(alias: string, cloningExpressionVisitor: ExpressionVisitor): TableExpressionBase;
    Equals(obj: unknown): boolean;
    Equals(expression: PgTableValuedFunctionExpression): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Update(arguments: IReadOnlyList_1<SqlExpression>): PgTableValuedFunctionExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
    WithAlias(newAlias: string): PgTableValuedFunctionExpression;
    WithColumnInfos(columnInfos: IReadOnlyList_1<PgTableValuedFunctionExpression_ColumnInfo>): PgTableValuedFunctionExpression;
}


export const PgTableValuedFunctionExpression: {
    new(alias: string, name: string, arguments: IReadOnlyList_1<SqlExpression>, columnInfos: IReadOnlyList_1<PgTableValuedFunctionExpression_ColumnInfo>, withOrdinality: boolean): PgTableValuedFunctionExpression;
};


export type PgTableValuedFunctionExpression = PgTableValuedFunctionExpression$instance;

export interface PgUnknownBinaryExpression$instance extends SqlExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgUnknownBinaryExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Left: SqlExpression;
    readonly Operator: string;
    readonly Right: SqlExpression;
    Equals(other: PgUnknownBinaryExpression): boolean;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    ToString(): string;
    Update(left: SqlExpression, right: SqlExpression): PgUnknownBinaryExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const PgUnknownBinaryExpression: {
    new(left: SqlExpression, right: SqlExpression, binaryOperator: string, type: Type, typeMapping: RelationalTypeMapping): PgUnknownBinaryExpression;
};


export type PgUnknownBinaryExpression = PgUnknownBinaryExpression$instance;

export interface PgUnnestExpression$instance extends PgTableValuedFunctionExpression {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Query_Expressions_Internal_PgUnnestExpression: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IPrintableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IRelationalQuotableExpression: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_SqlExpressions_ITableBasedExpression: never;
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Array: SqlExpression;
    readonly ColumnName: string;
    Clone(alias: string, cloningExpressionVisitor: ExpressionVisitor): TableExpressionBase;
    Update(arguments: IReadOnlyList_1<SqlExpression>): PgUnnestExpression;
    Update(array: SqlExpression): PgUnnestExpression;
    Update(arguments: IReadOnlyList_1<SqlExpression>): PgTableValuedFunctionExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
    WithAlias(newAlias: string): PgUnnestExpression;
    WithAlias(newAlias: string): PgTableValuedFunctionExpression;
    WithColumnInfos(columnInfos: IReadOnlyList_1<PgTableValuedFunctionExpression_ColumnInfo>): PgUnnestExpression;
    WithColumnInfos(columnInfos: IReadOnlyList_1<PgTableValuedFunctionExpression_ColumnInfo>): PgTableValuedFunctionExpression;
}


export const PgUnnestExpression: {
    new(alias: string, array: SqlExpression, columnName: string, withOrdinality: boolean): PgUnnestExpression;
};


export type PgUnnestExpression = PgUnnestExpression$instance;

