// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Internal
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Npgsql_EntityFrameworkCore_PostgreSQL_Infrastructure_Internal_Internal from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal/internal/index.js";
import type { EnumDefinition, INpgsqlSingletonOptions, UserRangeDefinition } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal/internal/index.js";
import type { IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString, Version, Void } from "@tsonic/dotnet/System.js";
import type { EventDefinition, FallbackEventDefinition, IDiagnosticsLogger } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { IDbContextOptions, ISingletonOptions } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { DbLoggerCategory$Scaffolding } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";

export interface NpgsqlSingletonOptions$instance {
    readonly EnumDefinitions: IReadOnlyList<EnumDefinition>;
    readonly IsPostgresVersionSet: boolean;
    readonly PostgresVersion: Version;
    readonly ReverseNullOrderingEnabled: boolean;
    readonly UseRedshift: boolean;
    readonly UserRangeDefinitions: IReadOnlyList<UserRangeDefinition>;
    Initialize(options: IDbContextOptions): void;
    Validate(options: IDbContextOptions): void;
}


export const NpgsqlSingletonOptions: {
    new(): NpgsqlSingletonOptions;
};


export interface __NpgsqlSingletonOptions$views {
    As_INpgsqlSingletonOptions(): Npgsql_EntityFrameworkCore_PostgreSQL_Infrastructure_Internal_Internal.INpgsqlSingletonOptions$instance;
}

export interface NpgsqlSingletonOptions$instance extends Npgsql_EntityFrameworkCore_PostgreSQL_Infrastructure_Internal_Internal.INpgsqlSingletonOptions$instance {}

export type NpgsqlSingletonOptions = NpgsqlSingletonOptions$instance & __NpgsqlSingletonOptions$views;


export abstract class NpgsqlLoggerExtensions$instance {
    static CollationFound(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, schema: string, collationName: string, lcCollate: string, lcCtype: string, provider: string, deterministic: boolean): void;
    static ColumnFound(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, tableName: string, columnName: string, dataTypeName: string, nullable: boolean, identity: boolean, defaultValue: string, computedValue: string): void;
    static EnumColumnSkippedWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, columnName: string): void;
    static ExpressionIndexSkippedWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, indexName: string, tableName: string): void;
    static ForeignKeyReferencesMissingPrincipalTableWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, foreignKeyName: string, tableName: string, principalTableName: string): void;
    static MissingSchemaWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, schemaName: string): void;
    static MissingTableWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, tableName: string): void;
    static UniqueConstraintFound(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, uniqueConstraintName: string, tableName: string): void;
    static UnsupportedColumnConstraintSkippedWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, indexName: string, tableName: string): void;
    static UnsupportedColumnIndexSkippedWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, indexName: string, tableName: string): void;
}


export type NpgsqlLoggerExtensions = NpgsqlLoggerExtensions$instance;

export abstract class NpgsqlResources$instance {
    static LogEnumColumnSkipped(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String>;
    static LogExpressionIndexSkipped(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String>;
    static LogFoundCollation(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String, System_Internal.String, System_Internal.String, string | undefined, System_Internal.Boolean>;
    static LogFoundColumn(logger: IDiagnosticsLogger): FallbackEventDefinition;
    static LogFoundForeignKey(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String, System_Internal.String, System_Internal.String>;
    static LogFoundIndex(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String, System_Internal.Boolean>;
    static LogFoundPrimaryKey(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String>;
    static LogFoundSequence(logger: IDiagnosticsLogger): FallbackEventDefinition;
    static LogFoundTable(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String>;
    static LogFoundUniqueConstraint(logger: IDiagnosticsLogger): EventDefinition<string | undefined, System_Internal.String>;
    static LogMissingSchema(logger: IDiagnosticsLogger): EventDefinition<string | undefined>;
    static LogMissingTable(logger: IDiagnosticsLogger): EventDefinition<string | undefined>;
    static LogPrincipalColumnNotFound(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String, System_Internal.String, System_Internal.String>;
    static LogPrincipalTableNotInSelectionSet(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined, string | undefined>;
    static LogUnsupportedColumnConstraintSkipped(logger: IDiagnosticsLogger): EventDefinition<string | undefined, System_Internal.String>;
    static LogUnsupportedColumnIndexSkipped(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String>;
}


export type NpgsqlResources = NpgsqlResources$instance;

export abstract class NpgsqlStrings$instance {
    static readonly DataSourceAndConfigNotSupported: string;
    static readonly Ef7JsonMappingNotSupported: string;
    static readonly FreeTextFunctionOnClient: string;
    static readonly RowValueComparisonRequiresTuplesOfSameLength: string;
    static readonly CannotUseDataSourceWithAuthCallbacks: string;
    static readonly TransientExceptionDetected: string;
    static DuplicateColumnCompressionMethodMismatch(entityType1: unknown, property1: unknown, entityType2: unknown, property2: unknown, columnName: unknown, table: unknown): string;
    static DuplicateColumnNameValueGenerationStrategyMismatch(entityType1: unknown, property1: unknown, entityType2: unknown, property2: unknown, columnName: unknown, table: unknown): string;
    static DuplicateIndexCollationMismatch(index1: unknown, entityType1: unknown, index2: unknown, entityType2: unknown, table: unknown, indexName: unknown): string;
    static DuplicateIndexConcurrentCreationMismatch(index1: unknown, entityType1: unknown, index2: unknown, entityType2: unknown, table: unknown, indexName: unknown): string;
    static DuplicateIndexIncludedMismatch(index1: unknown, entityType1: unknown, index2: unknown, entityType2: unknown, table: unknown, indexName: unknown, includedColumns1: unknown, includedColumns2: unknown): string;
    static HeterogeneousTypesInNewArray(type1: unknown, type2: unknown): string;
    static IdentityBadType(property: unknown, entityType: unknown, propertyType: unknown): string;
    static IncludePropertyDuplicated(entityType: unknown, property: unknown): string;
    static IncludePropertyInIndex(entityType: unknown, property: unknown): string;
    static IncludePropertyNotFound(entityType: unknown, property: unknown): string;
    static InvalidTableToIncludeInScaffolding(table: unknown): string;
    static NonKeyValueGeneration(property: unknown, entityType: unknown): string;
    static SequenceBadType(property: unknown, entityType: unknown, propertyType: unknown): string;
    static StoredProcedureResultColumnsNotSupported(entityType: unknown, sproc: unknown): string;
    static StoredProcedureReturnValueNotSupported(entityType: unknown, sproc: unknown): string;
    static TwoDataSourcesInSameServiceProvider(useInternalServiceProvider: unknown): string;
}


export type NpgsqlStrings = NpgsqlStrings$instance;

