// Generated by dotnet-bindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { Task, Task_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System/internal/index.js";
import type { IDiagnosticsLogger_1, IRelationalCommandDiagnosticsLogger } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import type { ICurrentDbContext, IDbContextOptions, IModelRuntimeInitializer } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IDesignTimeModel } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Migrations_Internal_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.Internal/internal/index.js";
import type { Migrator } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.Internal/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Migrations_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations/internal/index.js";
import type { HistoryRepository, HistoryRepositoryDependencies, HistoryRow, IHistoryRepository, IMigrationCommandExecutor, IMigrationsAssembly, IMigrationsDatabaseLock, IMigrationsModelDiffer, IMigrationsSqlGenerator, IMigrator, LockReleaseBehavior, MigrationCommand } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations/internal/index.js";
import type { IDatabaseCreator, IDatabaseProvider, IExecutionStrategy, IRawSqlCommandBuilder, IRelationalConnection, ISqlGenerationHelper } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { DbLoggerCategory_Migrations } from "@tsonic/efcore/Microsoft.EntityFrameworkCore/internal/index.js";

export interface NpgsqlHistoryRepository$instance extends Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_HistoryRepository: never;
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Migrations_Internal_NpgsqlHistoryRepository: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IHistoryRepository: never;

    AcquireDatabaseLock: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["AcquireDatabaseLock"] & (() => IMigrationsDatabaseLock);
    AcquireDatabaseLockAsync: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["AcquireDatabaseLockAsync"] & ((cancellationToken?: CancellationToken) => Task_1<IMigrationsDatabaseLock>);
    Exists: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["Exists"] & (() => boolean);
    ExistsAsync: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["ExistsAsync"] & ((cancellationToken?: CancellationToken) => Task_1<System_Internal.Boolean>);
    GetAppliedMigrations: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["GetAppliedMigrations"] & (() => IReadOnlyList_1<HistoryRow>);
    GetAppliedMigrationsAsync: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["GetAppliedMigrationsAsync"] & ((cancellationToken?: CancellationToken) => Task_1<IReadOnlyList_1<HistoryRow>>);
    GetBeginIfExistsScript: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["GetBeginIfExistsScript"] & ((migrationId: string) => string);
    GetBeginIfNotExistsScript: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["GetBeginIfNotExistsScript"] & ((migrationId: string) => string);
    GetCreateCommands: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["GetCreateCommands"] & (() => IReadOnlyList_1<MigrationCommand>);
    GetCreateIfNotExistsScript: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["GetCreateIfNotExistsScript"] & (() => string);
    GetEndIfScript: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["GetEndIfScript"] & (() => string);
    InterpretExistsResult: Microsoft_EntityFrameworkCore_Migrations_Internal.HistoryRepository["InterpretExistsResult"] & ((value: unknown | null) => boolean);
}


export const NpgsqlHistoryRepository: {
    new(dependencies: HistoryRepositoryDependencies): NpgsqlHistoryRepository;
};


export type NpgsqlHistoryRepository = NpgsqlHistoryRepository$instance;

export interface NpgsqlMigrator$instance extends Microsoft_EntityFrameworkCore_Migrations_Internal_Internal.Migrator {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Migrations_Internal_Migrator: never;
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Migrations_Internal_NpgsqlMigrator: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Migrations_IMigrator: never;

    Migrate: Microsoft_EntityFrameworkCore_Migrations_Internal_Internal.Migrator["Migrate"] & ((targetMigration: string | null) => void);
    MigrateAsync: Microsoft_EntityFrameworkCore_Migrations_Internal_Internal.Migrator["MigrateAsync"] & ((targetMigration: string | null, cancellationToken?: CancellationToken) => Task);
}


export const NpgsqlMigrator: {
    new(migrationsAssembly: IMigrationsAssembly, historyRepository: IHistoryRepository, databaseCreator: IDatabaseCreator, migrationsSqlGenerator: IMigrationsSqlGenerator, rawSqlCommandBuilder: IRawSqlCommandBuilder, migrationCommandExecutor: IMigrationCommandExecutor, connection: IRelationalConnection, sqlGenerationHelper: ISqlGenerationHelper, currentContext: ICurrentDbContext, modelRuntimeInitializer: IModelRuntimeInitializer, logger: IDiagnosticsLogger_1<DbLoggerCategory_Migrations>, commandLogger: IRelationalCommandDiagnosticsLogger, databaseProvider: IDatabaseProvider, migrationsModelDiffer: IMigrationsModelDiffer, designTimeModel: IDesignTimeModel, contextOptions: IDbContextOptions, executionStrategy: IExecutionStrategy): NpgsqlMigrator;
};


export type NpgsqlMigrator = NpgsqlMigrator$instance;
