// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Storage.ValueConversion
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.js";
import type { ValueConverter } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.ValueConversion.js";

export interface NpgsqlArrayConverter_3$instance<TModelCollection extends IEnumerable, TConcreteModelCollection extends IEnumerable, TProviderCollection extends IEnumerable> extends ValueConverter<TModelCollection, TProviderCollection> {
    readonly elementConverter: ValueConverter | undefined;
}


export const NpgsqlArrayConverter_3: {
    new<TModelCollection extends IEnumerable, TConcreteModelCollection extends IEnumerable, TProviderCollection extends IEnumerable>(): NpgsqlArrayConverter_3<TModelCollection, TConcreteModelCollection, TProviderCollection>;
    new<TModelCollection extends IEnumerable, TConcreteModelCollection extends IEnumerable, TProviderCollection extends IEnumerable>(elementConverter: ValueConverter): NpgsqlArrayConverter_3<TModelCollection, TConcreteModelCollection, TProviderCollection>;
};


export type NpgsqlArrayConverter_3<TModelCollection extends IEnumerable, TConcreteModelCollection extends IEnumerable, TProviderCollection extends IEnumerable> = NpgsqlArrayConverter_3$instance<TModelCollection, TConcreteModelCollection, TProviderCollection>;

