// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Design.Internal
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IDictionary, IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { ValueComparer } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.ChangeTracking.js";
import * as Microsoft_EntityFrameworkCore_Design_Internal_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Design.Internal.js";
import type { CSharpRuntimeAnnotationCodeGeneratorDependencies, CSharpRuntimeAnnotationCodeGeneratorParameters, RelationalCSharpRuntimeAnnotationCodeGenerator, RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Design.Internal.js";
import * as Microsoft_EntityFrameworkCore_Design_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Design.js";
import type { AnnotationCodeGenerator, AnnotationCodeGeneratorDependencies, IAnnotationCodeGenerator, IDesignTimeServices, MethodCallCodeFragment } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Design.js";
import type { IAnnotation } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { IColumn, IEntityType, IIndex, IModel, IProperty, IRelationalModel, ITable, ITableIndex } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import type { CoreTypeMapping } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";
import type { IServiceCollection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection.js";

export interface NpgsqlAnnotationCodeGenerator$instance extends AnnotationCodeGenerator {
    GenerateFluentApiCalls(model: IModel, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
    GenerateFluentApiCalls(property: IProperty, annotations: IDictionary<System_Internal.String, IAnnotation>): IReadOnlyList<MethodCallCodeFragment>;
}


export const NpgsqlAnnotationCodeGenerator: {
    new(dependencies: AnnotationCodeGeneratorDependencies): NpgsqlAnnotationCodeGenerator;
};


export type NpgsqlAnnotationCodeGenerator = NpgsqlAnnotationCodeGenerator$instance;

export interface NpgsqlCSharpRuntimeAnnotationCodeGenerator$instance extends RelationalCSharpRuntimeAnnotationCodeGenerator {
    Create(typeMapping: CoreTypeMapping, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters, valueComparer?: ValueComparer, keyValueComparer?: ValueComparer, providerValueComparer?: ValueComparer): boolean;
    Generate(model: IModel, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(model: IRelationalModel, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(property: IProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(column: IColumn, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(index: IIndex, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(index: ITableIndex, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(entityType: IEntityType, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(table: ITable, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
}


export const NpgsqlCSharpRuntimeAnnotationCodeGenerator: {
    new(dependencies: CSharpRuntimeAnnotationCodeGeneratorDependencies, relationalDependencies: RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies): NpgsqlCSharpRuntimeAnnotationCodeGenerator;
};


export type NpgsqlCSharpRuntimeAnnotationCodeGenerator = NpgsqlCSharpRuntimeAnnotationCodeGenerator$instance;

export interface NpgsqlDesignTimeServices$instance {
    ConfigureDesignTimeServices(serviceCollection: IServiceCollection): void;
}


export const NpgsqlDesignTimeServices: {
    new(): NpgsqlDesignTimeServices;
};


export type NpgsqlDesignTimeServices = NpgsqlDesignTimeServices$instance;

