// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.Conventions
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { EnumDefinition, INpgsqlSingletonOptions } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal/internal/index.js";
import type { NpgsqlTypeMappingSource } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal/internal/index.js";
import type { IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Nullable, Object as ClrObject, String as ClrString, Version, Void } from "@tsonic/dotnet/System.js";
import type { ModelBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import type { IConventionModelBuilder, IConventionPropertyBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Builders.js";
import * as Microsoft_EntityFrameworkCore_Metadata_Conventions_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure.js";
import type { IProviderConventionSetBuilder, ProviderConventionSetBuilderDependencies, RelationalConventionSetBuilder, RelationalConventionSetBuilderDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure.js";
import * as Microsoft_EntityFrameworkCore_Metadata_Conventions_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Conventions.js";
import type { ConventionSet, IConvention, IConventionContext, IEntityTypeAnnotationChangedConvention, IEntityTypeBaseTypeChangedConvention, IEntityTypePrimaryKeyChangedConvention, IForeignKeyAddedConvention, IForeignKeyOwnershipChangedConvention, IForeignKeyPropertiesChangedConvention, IForeignKeyRemovedConvention, IModelFinalizedConvention, IModelFinalizingConvention, IModelInitializedConvention, IPropertyAnnotationChangedConvention, RelationalRuntimeModelConvention, RelationalValueGenerationConvention, SharedTableConvention, StoreGenerationConvention } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Conventions.js";
import type { IConventionAnnotation, IReadOnlyProperty, StoreObjectIdentifier, ValueGenerated } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import type { IRelationalTypeMappingSource } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export interface NpgsqlConventionSetBuilder$instance extends RelationalConventionSetBuilder {
    createConventionSet(): ConventionSet;
}


export const NpgsqlConventionSetBuilder: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies, typeMappingSource: IRelationalTypeMappingSource, npgsqlSingletonOptions: INpgsqlSingletonOptions): NpgsqlConventionSetBuilder;
    build(): ConventionSet;
    createModelBuilder(): ModelBuilder;
};


export type NpgsqlConventionSetBuilder = NpgsqlConventionSetBuilder$instance;

export interface NpgsqlPostgresModelFinalizingConvention$instance {
    processModelFinalizing(modelBuilder: IConventionModelBuilder, context: IConventionContext<IConventionModelBuilder>): void;
}


export const NpgsqlPostgresModelFinalizingConvention: {
    new(typeMappingSource: NpgsqlTypeMappingSource, enumDefinitions: IReadOnlyList<EnumDefinition>): NpgsqlPostgresModelFinalizingConvention;
};


export type NpgsqlPostgresModelFinalizingConvention = NpgsqlPostgresModelFinalizingConvention$instance;

export interface NpgsqlRuntimeModelConvention$instance extends RelationalRuntimeModelConvention {
}


export const NpgsqlRuntimeModelConvention: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies): NpgsqlRuntimeModelConvention;
};


export type NpgsqlRuntimeModelConvention = NpgsqlRuntimeModelConvention$instance;

export interface NpgsqlSharedTableConvention$instance extends SharedTableConvention {
}


export const NpgsqlSharedTableConvention: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies): NpgsqlSharedTableConvention;
};


export type NpgsqlSharedTableConvention = NpgsqlSharedTableConvention$instance;

export interface NpgsqlStoreGenerationConvention$instance extends StoreGenerationConvention {
    processPropertyAnnotationChanged(propertyBuilder: IConventionPropertyBuilder, name: string, annotation: IConventionAnnotation, oldAnnotation: IConventionAnnotation, context: IConventionContext<IConventionAnnotation>): void;
}


export const NpgsqlStoreGenerationConvention: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies): NpgsqlStoreGenerationConvention;
};


export type NpgsqlStoreGenerationConvention = NpgsqlStoreGenerationConvention$instance;

export interface NpgsqlValueGenerationConvention$instance extends RelationalValueGenerationConvention {
    processPropertyAnnotationChanged(propertyBuilder: IConventionPropertyBuilder, name: string, annotation: IConventionAnnotation, oldAnnotation: IConventionAnnotation, context: IConventionContext<IConventionAnnotation>): void;
}


export const NpgsqlValueGenerationConvention: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies): NpgsqlValueGenerationConvention;
    getValueGenerated(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): Nullable<ValueGenerated>;
};


export type NpgsqlValueGenerationConvention = NpgsqlValueGenerationConvention$instance;

export interface NpgsqlValueGenerationStrategyConvention$instance {
    processModelFinalizing(modelBuilder: IConventionModelBuilder, context: IConventionContext<IConventionModelBuilder>): void;
    processModelInitialized(modelBuilder: IConventionModelBuilder, context: IConventionContext<IConventionModelBuilder>): void;
}


export const NpgsqlValueGenerationStrategyConvention: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies, postgresVersion: Version): NpgsqlValueGenerationStrategyConvention;
};


export type NpgsqlValueGenerationStrategyConvention = NpgsqlValueGenerationStrategyConvention$instance;

