// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import * as Npgsql_EntityFrameworkCore_PostgreSQL_Infrastructure_Internal_Internal from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal/internal/index.js";
import type { NpgsqlOptionsExtension } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal/internal/index.js";
import type { INpgsqlNameTranslator, NpgsqlDataSourceBuilder, ProvideClientCertificatesCallback, ProvidePasswordCallback } from "../../Npgsql/internal/index.js";
import type { ICollection_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { RemoteCertificateValidationCallback } from "@tsonic/dotnet/System.Net.Security/internal/index.js";
import type { Action_1, Boolean as ClrBoolean, Enum, Int32, Nullable_1, String as ClrString, TimeSpan, Type, ValueType, Version, Void } from "@tsonic/dotnet/System/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { EntityFrameworkRelationalServicesBuilder, IRelationalDbContextOptionsBuilderInfrastructure, RelationalDbContextOptionsBuilder_2, ServiceCharacteristics } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { DbContextOptionsBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore/internal/index.js";
import type { IServiceCollection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection/internal/index.js";

export interface INpgsqlDataSourceConfigurationPlugin$instance {
    readonly __tsonic_iface_Npgsql_EntityFrameworkCore_PostgreSQL_Infrastructure_INpgsqlDataSourceConfigurationPlugin: never;

    Configure(npgsqlDataSourceBuilder: NpgsqlDataSourceBuilder): void;
}


export type INpgsqlDataSourceConfigurationPlugin = INpgsqlDataSourceConfigurationPlugin$instance;

export interface EntityFrameworkNpgsqlServicesBuilder$instance extends EntityFrameworkRelationalServicesBuilder {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Infrastructure_EntityFrameworkNpgsqlServicesBuilder: never;

    TryGetServiceCharacteristics(serviceType: Type): Nullable_1<ServiceCharacteristics>;
}


export const EntityFrameworkNpgsqlServicesBuilder: {
    new(serviceCollection: IServiceCollection): EntityFrameworkNpgsqlServicesBuilder;
};


export type EntityFrameworkNpgsqlServicesBuilder = EntityFrameworkNpgsqlServicesBuilder$instance;

export interface NpgsqlDbContextOptionsBuilder$instance extends RelationalDbContextOptionsBuilder_2<NpgsqlDbContextOptionsBuilder, NpgsqlOptionsExtension> {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Infrastructure_NpgsqlDbContextOptionsBuilder: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IRelationalDbContextOptionsBuilderInfrastructure: never;

    ConfigureDataSource(dataSourceBuilderAction: Action_1<NpgsqlDataSourceBuilder>): NpgsqlDbContextOptionsBuilder;
    EnableRetryOnFailure(): NpgsqlDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int): NpgsqlDbContextOptionsBuilder;
    EnableRetryOnFailure(errorCodesToAdd: ICollection_1<System_Internal.String> | null): NpgsqlDbContextOptionsBuilder;
    EnableRetryOnFailure(maxRetryCount: int, maxRetryDelay: TimeSpan, errorCodesToAdd: ICollection_1<System_Internal.String> | null): NpgsqlDbContextOptionsBuilder;
    MapEnum<T extends NonNullable<unknown> & number>(enumName?: string | null, schemaName?: string | null, nameTranslator?: INpgsqlNameTranslator | null): NpgsqlDbContextOptionsBuilder;
    MapEnum(clrType: Type, enumName?: string | null, schemaName?: string | null, nameTranslator?: INpgsqlNameTranslator | null): NpgsqlDbContextOptionsBuilder;
    MapRange<TSubtype extends unknown>(rangeName: string, schemaName?: string | null, subtypeName?: string | null): NpgsqlDbContextOptionsBuilder;
    MapRange(rangeName: string, subtypeClrType: Type, schemaName?: string | null, subtypeName?: string | null): NpgsqlDbContextOptionsBuilder;
    ProvideClientCertificatesCallback(callback: ProvideClientCertificatesCallback | null): NpgsqlDbContextOptionsBuilder;
    ProvidePasswordCallback(callback: ProvidePasswordCallback | null): NpgsqlDbContextOptionsBuilder;
    RemoteCertificateValidationCallback(callback: RemoteCertificateValidationCallback | null): NpgsqlDbContextOptionsBuilder;
    SetPostgresVersion(postgresVersion: Version | null): NpgsqlDbContextOptionsBuilder;
    SetPostgresVersion(major: int, minor: int): NpgsqlDbContextOptionsBuilder;
    UseAdminDatabase(dbName: string | null): NpgsqlDbContextOptionsBuilder;
    UseRedshift(useRedshift?: boolean): NpgsqlDbContextOptionsBuilder;
}


export const NpgsqlDbContextOptionsBuilder: {
    new(optionsBuilder: DbContextOptionsBuilder): NpgsqlDbContextOptionsBuilder;
};


export type NpgsqlDbContextOptionsBuilder = NpgsqlDbContextOptionsBuilder$instance;

