// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Metadata
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { IEnumerable_1, IReadOnlyList_1, List_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Nullable_1, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System/internal/index.js";
import type { Annotatable, IReadOnlyAnnotatable } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IConventionAnnotatable, IMutableAnnotatable } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata/internal/index.js";

export enum NpgsqlValueGenerationStrategy {
    None = 0,
    SequenceHiLo = 1,
    SerialColumn = 2,
    IdentityAlwaysColumn = 3,
    IdentityByDefaultColumn = 4,
    Sequence = 5
}


export enum NullSortOrder {
    Unspecified = 0,
    NullsFirst = 1,
    NullsLast = 2
}


export enum SortOrder {
    Ascending = 0,
    Descending = 1
}


export interface CockroachDbInterleaveInParent$instance {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Metadata_CockroachDbInterleaveInParent: never;

    readonly Annotatable: Annotatable;
    InterleavePrefix: List_1<System_Internal.String>;
    ParentTableName: string;
    get ParentTableSchema(): string | null;
    set ParentTableSchema(value: string | null);
}


export const CockroachDbInterleaveInParent: {
    new(annotatable: IReadOnlyAnnotatable): CockroachDbInterleaveInParent;
};


export type CockroachDbInterleaveInParent = CockroachDbInterleaveInParent$instance;

export interface PostgresCollation$instance {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Metadata_PostgresCollation: never;

    readonly Annotatable: Annotatable;
    get IsDeterministic(): Nullable_1<System_Internal.Boolean>;
    set IsDeterministic(value: Nullable_1<System_Internal.Boolean> | boolean);
    LcCollate: string;
    LcCtype: string;
    readonly Name: string;
    get Provider(): string | null;
    set Provider(value: string | null);
    readonly Schema: string | null;
}


export const PostgresCollation: {
    FindCollation(annotatable: IReadOnlyAnnotatable, schema: string | null, name: string): PostgresCollation | null;
    GetCollations(annotatable: IReadOnlyAnnotatable): IEnumerable_1<PostgresCollation>;
    GetOrAddCollation(annotatable: IMutableAnnotatable, schema: string | null, name: string, lcCollate: string, lcCtype: string, provider?: string | null, deterministic?: Nullable_1<System_Internal.Boolean>): PostgresCollation;
};


export type PostgresCollation = PostgresCollation$instance;

export interface PostgresEnum$instance {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Metadata_PostgresEnum: never;

    readonly Annotatable: Annotatable;
    Labels: IReadOnlyList_1<System_Internal.String>;
    readonly Name: string;
    readonly Schema: string | null;
}


export const PostgresEnum: {
    FindPostgresEnum(annotatable: IReadOnlyAnnotatable, schema: string | null, name: string): PostgresEnum | null;
    GetOrAddPostgresEnum(annotatable: IConventionAnnotatable, schema: string | null, name: string, labels: string[]): PostgresEnum;
    GetOrAddPostgresEnum(annotatable: IMutableAnnotatable, schema: string | null, name: string, labels: string[]): PostgresEnum;
    GetOrAddPostgresEnum(annotatable: IMutableAnnotatable, name: string, labels: string[]): PostgresEnum;
    GetPostgresEnums(annotatable: IReadOnlyAnnotatable): IEnumerable_1<PostgresEnum>;
};


export type PostgresEnum = PostgresEnum$instance;

export interface PostgresExtension$instance {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Metadata_PostgresExtension: never;

    readonly Annotatable: Annotatable;
    readonly Name: string;
    readonly Schema: string | null;
    get Version(): string | null;
    set Version(value: string | null);
}


export const PostgresExtension: {
    FindPostgresExtension(annotatable: IReadOnlyAnnotatable, schema: string | null, name: string): PostgresExtension | null;
    GetOrAddPostgresExtension(annotatable: IConventionAnnotatable, schema: string | null, name: string, version: string | null): PostgresExtension;
    GetOrAddPostgresExtension(annotatable: IMutableAnnotatable, schema: string | null, name: string, version: string | null): PostgresExtension;
    GetOrAddPostgresExtension(annotatable: IMutableAnnotatable, name: string, version: string | null): PostgresExtension;
    GetPostgresExtensions(annotatable: IReadOnlyAnnotatable): IEnumerable_1<PostgresExtension>;
};


export type PostgresExtension = PostgresExtension$instance;

export interface PostgresRange$instance {
    readonly __tsonic_type_Npgsql_EntityFrameworkCore_PostgreSQL_Metadata_PostgresRange: never;

    readonly Annotatable: Annotatable;
    get CanonicalFunction(): string | null;
    set CanonicalFunction(value: string | null);
    get Collation(): string | null;
    set Collation(value: string | null);
    readonly Name: string;
    readonly Schema: string | null;
    Subtype: string;
    get SubtypeDiff(): string | null;
    set SubtypeDiff(value: string | null);
    get SubtypeOpClass(): string | null;
    set SubtypeOpClass(value: string | null);
}


export const PostgresRange: {
    FindPostgresRange(annotatable: IReadOnlyAnnotatable, schema: string | null, name: string): PostgresRange | null;
    GetOrAddPostgresRange(annotatable: IMutableAnnotatable, schema: string | null, name: string, subtype: string, canonicalFunction?: string | null, subtypeOpClass?: string | null, collation?: string | null, subtypeDiff?: string | null): PostgresRange;
    GetPostgresRanges(annotatable: IReadOnlyAnnotatable): IEnumerable_1<PostgresRange>;
};


export type PostgresRange = PostgresRange$instance;

export abstract class NpgsqlValueGenerationStrategyExtensions$instance {
    static IsIdentity(strategy: NpgsqlValueGenerationStrategy): boolean;
    static IsIdentity(strategy: Nullable_1<NpgsqlValueGenerationStrategy>): boolean;
}


export type NpgsqlValueGenerationStrategyExtensions = NpgsqlValueGenerationStrategyExtensions$instance;

