// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Metadata
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IEnumerable, IReadOnlyList, List } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Nullable, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";
import type { Annotatable, IReadOnlyAnnotatable } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { IConventionAnnotatable, IMutableAnnotatable } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";

export enum NpgsqlValueGenerationStrategy {
    none = 0,
    sequenceHiLo = 1,
    serialColumn = 2,
    identityAlwaysColumn = 3,
    identityByDefaultColumn = 4,
    sequence = 5
}


export enum NullSortOrder {
    unspecified = 0,
    nullsFirst = 1,
    nullsLast = 2
}


export enum SortOrder {
    ascending = 0,
    descending = 1
}


export interface CockroachDbInterleaveInParent$instance {
    readonly annotatable: Annotatable;
    interleavePrefix: List<System_Internal.String>;
    parentTableName: string;
    get parentTableSchema(): string | undefined;
    set parentTableSchema(value: string);
}


export const CockroachDbInterleaveInParent: {
    new(annotatable: IReadOnlyAnnotatable): CockroachDbInterleaveInParent;
};


export type CockroachDbInterleaveInParent = CockroachDbInterleaveInParent$instance;

export interface PostgresCollation$instance {
    readonly annotatable: Annotatable;
    isDeterministic: Nullable<System_Internal.Boolean>;
    lcCollate: string;
    lcCtype: string;
    readonly name: string;
    get provider(): string | undefined;
    set provider(value: string);
    readonly schema: string | undefined;
}


export const PostgresCollation: {
    new(): PostgresCollation;
    findCollation(annotatable: IReadOnlyAnnotatable, schema: string, name: string): PostgresCollation | undefined;
    getCollations(annotatable: IReadOnlyAnnotatable): IEnumerable<PostgresCollation>;
    getOrAddCollation(annotatable: IMutableAnnotatable, schema: string, name: string, lcCollate: string, lcCtype: string, provider?: string, deterministic?: Nullable<System_Internal.Boolean>): PostgresCollation;
};


export type PostgresCollation = PostgresCollation$instance;

export interface PostgresEnum$instance {
    readonly annotatable: Annotatable;
    labels: IReadOnlyList<System_Internal.String>;
    readonly name: string;
    readonly schema: string | undefined;
}


export const PostgresEnum: {
    new(): PostgresEnum;
    findPostgresEnum(annotatable: IReadOnlyAnnotatable, schema: string, name: string): PostgresEnum | undefined;
    getOrAddPostgresEnum(annotatable: IConventionAnnotatable, schema: string, name: string, labels: string[]): PostgresEnum;
    getOrAddPostgresEnum(annotatable: IMutableAnnotatable, schema: string, name: string, labels: string[]): PostgresEnum;
    getOrAddPostgresEnum(annotatable: IMutableAnnotatable, name: string, labels: string[]): PostgresEnum;
    getPostgresEnums(annotatable: IReadOnlyAnnotatable): IEnumerable<PostgresEnum>;
};


export type PostgresEnum = PostgresEnum$instance;

export interface PostgresExtension$instance {
    readonly annotatable: Annotatable;
    readonly name: string;
    readonly schema: string | undefined;
    version: string;
}


export const PostgresExtension: {
    new(): PostgresExtension;
    findPostgresExtension(annotatable: IReadOnlyAnnotatable, schema: string, name: string): PostgresExtension | undefined;
    getOrAddPostgresExtension(annotatable: IConventionAnnotatable, schema: string, name: string, version: string): PostgresExtension;
    getOrAddPostgresExtension(annotatable: IMutableAnnotatable, schema: string, name: string, version: string): PostgresExtension;
    getOrAddPostgresExtension(annotatable: IMutableAnnotatable, name: string, version: string): PostgresExtension;
    getPostgresExtensions(annotatable: IReadOnlyAnnotatable): IEnumerable<PostgresExtension>;
};


export type PostgresExtension = PostgresExtension$instance;

export interface PostgresRange$instance {
    readonly annotatable: Annotatable;
    get canonicalFunction(): string | undefined;
    set canonicalFunction(value: string);
    get collation(): string | undefined;
    set collation(value: string);
    readonly name: string;
    readonly schema: string | undefined;
    subtype: string;
    get subtypeDiff(): string | undefined;
    set subtypeDiff(value: string);
    get subtypeOpClass(): string | undefined;
    set subtypeOpClass(value: string);
}


export const PostgresRange: {
    new(): PostgresRange;
    findPostgresRange(annotatable: IReadOnlyAnnotatable, schema: string, name: string): PostgresRange | undefined;
    getOrAddPostgresRange(annotatable: IMutableAnnotatable, schema: string, name: string, subtype: string, canonicalFunction?: string, subtypeOpClass?: string, collation?: string, subtypeDiff?: string): PostgresRange;
    getPostgresRanges(annotatable: IReadOnlyAnnotatable): IEnumerable<PostgresRange>;
};


export type PostgresRange = PostgresRange$instance;

export abstract class NpgsqlValueGenerationStrategyExtensions$instance {
    static isIdentity(strategy: NpgsqlValueGenerationStrategy): boolean;
    static isIdentity(strategy: Nullable<NpgsqlValueGenerationStrategy>): boolean;
}


export type NpgsqlValueGenerationStrategyExtensions = NpgsqlValueGenerationStrategyExtensions$instance;

