// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Query.Internal
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { INpgsqlSingletonOptions } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal/internal/index.js";
import type { IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Enum, IComparable, IConvertible, IFormattable, Int32, ISpanFormattable, Object as ClrObject, String as ClrString, Type, Version } from "@tsonic/dotnet/System.js";
import * as System_Linq_Expressions_Internal from "@tsonic/dotnet/System.Linq.Expressions.js";
import type { Expression, ExpressionVisitor } from "@tsonic/dotnet/System.Linq.Expressions.js";
import type { IModel } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import * as Microsoft_EntityFrameworkCore_Query_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.js";
import type { CompiledQueryCacheKeyGeneratorDependencies, EvaluatableExpressionFilterDependencies, ICompiledQueryCacheKeyGenerator, IEvaluatableExpressionFilter, IQueryableMethodTranslatingExpressionVisitorFactory, IQueryCompilationContextFactory, IQuerySqlGeneratorFactory, IQueryTranslationPostprocessorFactory, IRelationalParameterBasedSqlProcessorFactory, IRelationalSqlTranslatingExpressionVisitorFactory, ParametersCacheDecorator, QueryableMethodTranslatingExpressionVisitor, QueryableMethodTranslatingExpressionVisitorDependencies, QueryCompilationContext, QueryCompilationContextDependencies, QueryContext, QuerySqlGenerator, QuerySqlGeneratorDependencies, QueryTranslationPostprocessor, QueryTranslationPostprocessorDependencies, RelationalCompiledQueryCacheKeyGenerator, RelationalCompiledQueryCacheKeyGeneratorDependencies, RelationalEvaluatableExpressionFilter, RelationalEvaluatableExpressionFilterDependencies, RelationalParameterBasedSqlProcessor, RelationalParameterBasedSqlProcessorDependencies, RelationalParameterBasedSqlProcessorParameters, RelationalQueryableMethodTranslatingExpressionVisitor, RelationalQueryableMethodTranslatingExpressionVisitorDependencies, RelationalQueryCompilationContext, RelationalQueryCompilationContextDependencies, RelationalQueryTranslationPostprocessor, RelationalQueryTranslationPostprocessorDependencies, RelationalSqlTranslatingExpressionVisitor, RelationalSqlTranslatingExpressionVisitorDependencies, RelationalTypeMappingPostprocessor, SqlNullabilityProcessor, SqlTreePruner } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.js";
import type { SqlExpression } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.SqlExpressions.js";
import type { IRelationalTypeMappingSource } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export enum NpgsqlSqlTranslatingExpressionVisitor_StartsEndsWithContains {
    StartsWith = 0,
    EndsWith = 1,
    Contains = 2
}


export interface NpgsqlCompiledQueryCacheKeyGenerator$instance extends RelationalCompiledQueryCacheKeyGenerator {
    GenerateCacheKey(query: Expression, async: boolean): unknown;
}


export const NpgsqlCompiledQueryCacheKeyGenerator: {
    new(dependencies: CompiledQueryCacheKeyGeneratorDependencies, relationalDependencies: RelationalCompiledQueryCacheKeyGeneratorDependencies): NpgsqlCompiledQueryCacheKeyGenerator;
};


export type NpgsqlCompiledQueryCacheKeyGenerator = NpgsqlCompiledQueryCacheKeyGenerator$instance;

export interface NpgsqlDeleteConvertingExpressionVisitor$instance extends ExpressionVisitor {
    Process(node: Expression): Expression;
}


export const NpgsqlDeleteConvertingExpressionVisitor: {
    new(): NpgsqlDeleteConvertingExpressionVisitor;
};


export type NpgsqlDeleteConvertingExpressionVisitor = NpgsqlDeleteConvertingExpressionVisitor$instance;

export interface NpgsqlEvaluatableExpressionFilter$instance extends RelationalEvaluatableExpressionFilter {
    IsEvaluatableExpression(expression: Expression, model: IModel): boolean;
}


export const NpgsqlEvaluatableExpressionFilter: {
    new(dependencies: EvaluatableExpressionFilterDependencies, relationalDependencies: RelationalEvaluatableExpressionFilterDependencies, npgsqlSingletonOptions: INpgsqlSingletonOptions): NpgsqlEvaluatableExpressionFilter;
};


export type NpgsqlEvaluatableExpressionFilter = NpgsqlEvaluatableExpressionFilter$instance;

export interface NpgsqlParameterBasedSqlProcessor$instance extends RelationalParameterBasedSqlProcessor {
    Process(queryExpression: Expression, parametersDecorator: ParametersCacheDecorator): Expression;
}


export const NpgsqlParameterBasedSqlProcessor: {
    new(dependencies: RelationalParameterBasedSqlProcessorDependencies, parameters: RelationalParameterBasedSqlProcessorParameters): NpgsqlParameterBasedSqlProcessor;
};


export type NpgsqlParameterBasedSqlProcessor = NpgsqlParameterBasedSqlProcessor$instance;

export interface NpgsqlParameterBasedSqlProcessorFactory$instance {
    Create(parameters: RelationalParameterBasedSqlProcessorParameters): RelationalParameterBasedSqlProcessor;
}


export const NpgsqlParameterBasedSqlProcessorFactory: {
    new(dependencies: RelationalParameterBasedSqlProcessorDependencies): NpgsqlParameterBasedSqlProcessorFactory;
};


export type NpgsqlParameterBasedSqlProcessorFactory = NpgsqlParameterBasedSqlProcessorFactory$instance;

export interface NpgsqlQueryableMethodTranslatingExpressionVisitor$instance extends RelationalQueryableMethodTranslatingExpressionVisitor {
}


export const NpgsqlQueryableMethodTranslatingExpressionVisitor: {
    new(dependencies: QueryableMethodTranslatingExpressionVisitorDependencies, relationalDependencies: RelationalQueryableMethodTranslatingExpressionVisitorDependencies, queryCompilationContext: RelationalQueryCompilationContext, npgsqlSingletonOptions: INpgsqlSingletonOptions): NpgsqlQueryableMethodTranslatingExpressionVisitor;
};


export type NpgsqlQueryableMethodTranslatingExpressionVisitor = NpgsqlQueryableMethodTranslatingExpressionVisitor$instance;

export interface NpgsqlQueryableMethodTranslatingExpressionVisitorFactory$instance {
    Create(queryCompilationContext: QueryCompilationContext): QueryableMethodTranslatingExpressionVisitor;
}


export const NpgsqlQueryableMethodTranslatingExpressionVisitorFactory: {
    new(dependencies: QueryableMethodTranslatingExpressionVisitorDependencies, relationalDependencies: RelationalQueryableMethodTranslatingExpressionVisitorDependencies, npgsqlSingletonOptions: INpgsqlSingletonOptions): NpgsqlQueryableMethodTranslatingExpressionVisitorFactory;
};


export type NpgsqlQueryableMethodTranslatingExpressionVisitorFactory = NpgsqlQueryableMethodTranslatingExpressionVisitorFactory$instance;

export interface NpgsqlQueryCompilationContext$instance extends RelationalQueryCompilationContext {
    readonly IsBuffering: boolean;
    readonly SupportsPrecompiledQuery: boolean;
}


export const NpgsqlQueryCompilationContext: {
    new(dependencies: QueryCompilationContextDependencies, relationalDependencies: RelationalQueryCompilationContextDependencies, async: boolean): NpgsqlQueryCompilationContext;
    new(dependencies: QueryCompilationContextDependencies, relationalDependencies: RelationalQueryCompilationContextDependencies, async: boolean, precompiling: boolean): NpgsqlQueryCompilationContext;
};


export type NpgsqlQueryCompilationContext = NpgsqlQueryCompilationContext$instance;

export interface NpgsqlQueryCompilationContextFactory$instance {
    Create(async: boolean): QueryCompilationContext;
    CreatePrecompiled(async: boolean): QueryCompilationContext;
}


export const NpgsqlQueryCompilationContextFactory: {
    new(dependencies: QueryCompilationContextDependencies, relationalDependencies: RelationalQueryCompilationContextDependencies): NpgsqlQueryCompilationContextFactory;
};


export type NpgsqlQueryCompilationContextFactory = NpgsqlQueryCompilationContextFactory$instance;

export interface NpgsqlQuerySqlGenerator$instance extends QuerySqlGenerator {
}


export const NpgsqlQuerySqlGenerator: {
    new(dependencies: QuerySqlGeneratorDependencies, typeMappingSource: IRelationalTypeMappingSource, reverseNullOrderingEnabled: boolean, postgresVersion: Version): NpgsqlQuerySqlGenerator;
};


export type NpgsqlQuerySqlGenerator = NpgsqlQuerySqlGenerator$instance;

export interface NpgsqlQuerySqlGeneratorFactory$instance {
    Create(): QuerySqlGenerator;
}


export const NpgsqlQuerySqlGeneratorFactory: {
    new(dependencies: QuerySqlGeneratorDependencies, typeMappingSource: IRelationalTypeMappingSource, npgsqlSingletonOptions: INpgsqlSingletonOptions): NpgsqlQuerySqlGeneratorFactory;
};


export type NpgsqlQuerySqlGeneratorFactory = NpgsqlQuerySqlGeneratorFactory$instance;

export interface NpgsqlQueryTranslationPostprocessor$instance extends RelationalQueryTranslationPostprocessor {
    Process(query: Expression): Expression;
}


export const NpgsqlQueryTranslationPostprocessor: {
    new(dependencies: QueryTranslationPostprocessorDependencies, relationalDependencies: RelationalQueryTranslationPostprocessorDependencies, queryCompilationContext: RelationalQueryCompilationContext): NpgsqlQueryTranslationPostprocessor;
};


export type NpgsqlQueryTranslationPostprocessor = NpgsqlQueryTranslationPostprocessor$instance;

export interface NpgsqlQueryTranslationPostprocessorFactory$instance {
    Create(queryCompilationContext: QueryCompilationContext): QueryTranslationPostprocessor;
}


export const NpgsqlQueryTranslationPostprocessorFactory: {
    new(dependencies: QueryTranslationPostprocessorDependencies, relationalDependencies: RelationalQueryTranslationPostprocessorDependencies): NpgsqlQueryTranslationPostprocessorFactory;
};


export type NpgsqlQueryTranslationPostprocessorFactory = NpgsqlQueryTranslationPostprocessorFactory$instance;

export interface NpgsqlSetOperationTypingInjector$instance extends ExpressionVisitor {
}


export const NpgsqlSetOperationTypingInjector: {
    new(): NpgsqlSetOperationTypingInjector;
};


export type NpgsqlSetOperationTypingInjector = NpgsqlSetOperationTypingInjector$instance;

export interface NpgsqlSqlNullabilityProcessor$instance extends SqlNullabilityProcessor {
}


export const NpgsqlSqlNullabilityProcessor: {
    new(dependencies: RelationalParameterBasedSqlProcessorDependencies, parameters: RelationalParameterBasedSqlProcessorParameters): NpgsqlSqlNullabilityProcessor;
};


export type NpgsqlSqlNullabilityProcessor = NpgsqlSqlNullabilityProcessor$instance;

export interface NpgsqlSqlTranslatingExpressionVisitor$instance extends RelationalSqlTranslatingExpressionVisitor {
    GenerateGreatest(expressions: IReadOnlyList<SqlExpression>, resultType: Type): SqlExpression;
    GenerateLeast(expressions: IReadOnlyList<SqlExpression>, resultType: Type): SqlExpression;
}


export const NpgsqlSqlTranslatingExpressionVisitor: {
    new(dependencies: RelationalSqlTranslatingExpressionVisitorDependencies, queryCompilationContext: QueryCompilationContext, queryableMethodTranslatingExpressionVisitor: QueryableMethodTranslatingExpressionVisitor): NpgsqlSqlTranslatingExpressionVisitor;
    ConstructLikePatternParameter(queryContext: QueryContext, baseParameterName: string, methodType: NpgsqlSqlTranslatingExpressionVisitor_StartsEndsWithContains): string | undefined;
};


export type NpgsqlSqlTranslatingExpressionVisitor = NpgsqlSqlTranslatingExpressionVisitor$instance;

export interface NpgsqlSqlTranslatingExpressionVisitorFactory$instance {
    Create(queryCompilationContext: QueryCompilationContext, queryableMethodTranslatingExpressionVisitor: QueryableMethodTranslatingExpressionVisitor): RelationalSqlTranslatingExpressionVisitor;
}


export const NpgsqlSqlTranslatingExpressionVisitorFactory: {
    new(dependencies: RelationalSqlTranslatingExpressionVisitorDependencies): NpgsqlSqlTranslatingExpressionVisitorFactory;
};


export type NpgsqlSqlTranslatingExpressionVisitorFactory = NpgsqlSqlTranslatingExpressionVisitorFactory$instance;

export interface NpgsqlSqlTreePruner$instance extends SqlTreePruner {
}


export const NpgsqlSqlTreePruner: {
    new(): NpgsqlSqlTreePruner;
};


export type NpgsqlSqlTreePruner = NpgsqlSqlTreePruner$instance;

export interface NpgsqlTypeMappingPostprocessor$instance extends RelationalTypeMappingPostprocessor {
}


export const NpgsqlTypeMappingPostprocessor: {
    new(dependencies: QueryTranslationPostprocessorDependencies, relationalDependencies: RelationalQueryTranslationPostprocessorDependencies, queryCompilationContext: RelationalQueryCompilationContext): NpgsqlTypeMappingPostprocessor;
};


export type NpgsqlTypeMappingPostprocessor = NpgsqlTypeMappingPostprocessor$instance;

export interface NpgsqlUnnestPostprocessor$instance extends ExpressionVisitor {
    Visit(expression: Expression): Expression | undefined;
}


export const NpgsqlUnnestPostprocessor: {
    new(): NpgsqlUnnestPostprocessor;
};


export type NpgsqlUnnestPostprocessor = NpgsqlUnnestPostprocessor$instance;

