// Generated by tsbindgen - Architecture
// Namespace: Npgsql.Schema
// Assembly: Npgsql

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { PostgresType } from "../../Npgsql.PostgresTypes/internal/index.js";
import type { NpgsqlDbType } from "../../NpgsqlTypes/internal/index.js";
import * as System_Data_Common_Internal from "@tsonic/dotnet/System.Data.Common.js";
import type { DbColumn } from "@tsonic/dotnet/System.Data.Common.js";
import type { Boolean as ClrBoolean, Int16, Int32, Nullable, Object as ClrObject, String as ClrString, Type, UInt32 } from "@tsonic/dotnet/System.js";

export interface NpgsqlDbColumn$instance extends DbColumn {
    AllowDBNull: Nullable<System_Internal.Boolean>;
    BaseCatalogName: string;
    get BaseColumnName(): string | undefined;
    set BaseColumnName(value: string | undefined);
    get BaseSchemaName(): string | undefined;
    set BaseSchemaName(value: string | undefined);
    BaseServerName: string;
    get BaseTableName(): string | undefined;
    set BaseTableName(value: string | undefined);
    ColumnAttributeNumber: Nullable<System_Internal.Int16>;
    ColumnName: string;
    ColumnOrdinal: Nullable<System_Internal.Int32>;
    ColumnSize: Nullable<System_Internal.Int32>;
    get DataType(): Type | undefined;
    set DataType(value: Type | undefined);
    DataTypeName: string;
    get DefaultValue(): string | undefined;
    set DefaultValue(value: string | undefined);
    IsAliased: Nullable<System_Internal.Boolean>;
    IsAutoIncrement: Nullable<System_Internal.Boolean>;
    IsIdentity: Nullable<System_Internal.Boolean>;
    IsKey: Nullable<System_Internal.Boolean>;
    IsLong: Nullable<System_Internal.Boolean>;
    IsReadOnly: Nullable<System_Internal.Boolean>;
    IsUnique: Nullable<System_Internal.Boolean>;
    readonly [propertyName: string]: unknown | undefined;
    NpgsqlDbType: Nullable<NpgsqlDbType>;
    NumericPrecision: Nullable<System_Internal.Int32>;
    NumericScale: Nullable<System_Internal.Int32>;
    PostgresType: PostgresType;
    TableOID: uint;
    TypeOID: uint;
    get UdtAssemblyQualifiedName(): string | undefined;
    set UdtAssemblyQualifiedName(value: string | undefined);
}


export const NpgsqlDbColumn: {
    new(): NpgsqlDbColumn;
};


export type NpgsqlDbColumn = NpgsqlDbColumn$instance;

