// Generated by tsbindgen - Architecture
// Namespace: Npgsql
// Assembly: Npgsql

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { DbTypeResolverFactory, PgTypeInfoResolverFactory } from "../../Npgsql.Internal/internal/index.js";
import type { PostgresType } from "../../Npgsql.PostgresTypes/internal/index.js";
import type { NpgsqlDbColumn } from "../../Npgsql.Schema/internal/index.js";
import * as Npgsql_TypeMapping_Internal from "../../Npgsql.TypeMapping/internal/index.js";
import type { INpgsqlTypeMapper } from "../../Npgsql.TypeMapping/internal/index.js";
import type { NpgsqlDbType } from "../../NpgsqlTypes/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { ICollection_1, IDictionary_2, IEnumerable_1, IEnumerator_1, IList_1, IReadOnlyDictionary_2, IReadOnlyList_1, KeyValuePair_2 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { ReadOnlyCollection_1 } from "@tsonic/dotnet/System.Collections.ObjectModel/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { Hashtable, ICollection, IDictionary, IEnumerable, IEnumerator, IList } from "@tsonic/dotnet/System.Collections/internal/index.js";
import * as System_ComponentModel_Internal from "@tsonic/dotnet/System.ComponentModel/internal/index.js";
import type { IComponent, ICustomTypeDescriptor } from "@tsonic/dotnet/System.ComponentModel/internal/index.js";
import * as System_Data_Common_Internal from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import type { DataTableMapping, DbBatch, DbBatchCommand, DbBatchCommandCollection, DbColumn, DbCommand, DbCommandBuilder, DbConnection, DbConnectionStringBuilder, DbDataAdapter, DbDataReader, DbDataSource, DbException, DbParameter, DbParameterCollection, DbProviderFactory, DbTransaction, IDbColumnSchemaGenerator, RowUpdatedEventArgs, RowUpdatingEventArgs } from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import * as System_Data_Internal from "@tsonic/dotnet/System.Data/internal/index.js";
import type { CommandBehavior, CommandType, ConnectionState, DataRow, DataRowVersion, DataTable, DbType, IDataAdapter, IDataParameter, IDataParameterCollection, IDataReader, IDataRecord, IDbCommand, IDbConnection, IDbDataAdapter, IDbDataParameter, IDbTransaction, IsolationLevel, ParameterDirection, StatementType as StatementType_Data, UpdateRowSource } from "@tsonic/dotnet/System.Data/internal/index.js";
import type { Activity } from "@tsonic/dotnet/System.Diagnostics/internal/index.js";
import * as System_IO_Internal from "@tsonic/dotnet/System.IO/internal/index.js";
import type { SeekOrigin, Stream, StreamReader, StreamWriter, TextReader } from "@tsonic/dotnet/System.IO/internal/index.js";
import type { NegotiateAuthenticationClientOptions, RemoteCertificateValidationCallback, SslClientAuthenticationOptions } from "@tsonic/dotnet/System.Net.Security/internal/index.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { ISerializable, SerializationInfo, StreamingContext } from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { X509Certificate, X509Certificate2, X509Certificate2Collection, X509CertificateCollection } from "@tsonic/dotnet/System.Security.Cryptography.X509Certificates/internal/index.js";
import type { JsonSerializerOptions } from "@tsonic/dotnet/System.Text.Json/internal/index.js";
import type { Task, Task_1, ValueTask, ValueTask_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import type { Transaction } from "@tsonic/dotnet/System.Transactions/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Action_2, Array as ClrArray, AsyncCallback, Boolean as ClrBoolean, Byte, Char, DateTime, Decimal, Double, Enum, EventArgs, EventHandler, Exception, Func_1, Func_2, Func_3, Guid, IAsyncDisposable, IAsyncResult, ICloneable, IComparable, IConvertible, IDisposable, IFormattable, Int16, Int32, Int64, IntPtr, IServiceProvider, ISpanFormattable, Memory_1, MulticastDelegate, Nullable_1, Object as ClrObject, ReadOnlyMemory_1, ReadOnlySpan_1, Single, Span_1, String as ClrString, TimeSpan, Type, UInt32, UInt64, ValueType, Version, Void } from "@tsonic/dotnet/System/internal/index.js";
import type { ILoggerFactory } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging/internal/index.js";

export enum ArrayNullabilityMode {
    Never = 0,
    Always = 1,
    PerInstance = 2
}


export enum ChannelBinding {
    Disable = 0,
    Prefer = 1,
    Require = 2
}


export enum GssEncryptionMode {
    Disable = 0,
    Prefer = 1,
    Require = 2
}


export enum ServerCompatibilityMode {
    None = 0,
    Redshift = 1,
    NoTypeLoading = 2
}


export enum SslMode {
    Disable = 0,
    Allow = 1,
    Prefer = 2,
    Require = 3,
    VerifyCA = 4,
    VerifyFull = 5
}


export enum SslNegotiation {
    Postgres = 0,
    Direct = 1
}


export enum StatementType {
    Unknown = 0,
    Select = 1,
    Insert = 2,
    Delete = 3,
    Update = 4,
    CreateTableAs = 5,
    Move = 6,
    Fetch = 7,
    Copy = 8,
    Other = 9,
    Merge = 10,
    Call = 11
}


export enum TargetSessionAttributes {
    Any = 0,
    ReadWrite = 1,
    ReadOnly = 2,
    Primary = 3,
    Standby = 4,
    PreferPrimary = 5,
    PreferStandby = 6
}


export type NoticeEventHandler = (sender: unknown, e: NpgsqlNoticeEventArgs) => void;


export type NotificationEventHandler = (sender: unknown, e: NpgsqlNotificationEventArgs) => void;


export type NpgsqlRowUpdatedEventHandler = (sender: unknown, e: NpgsqlRowUpdatedEventArgs) => void;


export type NpgsqlRowUpdatingEventHandler = (sender: unknown, e: NpgsqlRowUpdatingEventArgs) => void;


export type ProvideClientCertificatesCallback = (certificates: X509CertificateCollection) => void;


export type ProvidePasswordCallback = (host: string, port: int, database: string, username: string) => string;


export interface INpgsqlNameTranslator$instance {
    readonly __tsonic_iface_Npgsql_INpgsqlNameTranslator: never;

    TranslateTypeName(clrName: string): string;
}


export type INpgsqlNameTranslator = INpgsqlNameTranslator$instance;

export interface NpgsqlBatch$instance extends DbBatch {
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly BatchCommands: NpgsqlBatchCommandCollection;
    get Connection(): NpgsqlConnection | undefined;
    set Connection(value: NpgsqlConnection | undefined);
    readonly DbBatchCommands: DbBatchCommandCollection;
    get DbConnection(): DbConnection | undefined;
    set DbConnection(value: DbConnection | undefined);
    get DbTransaction(): DbTransaction | undefined;
    set DbTransaction(value: DbTransaction | undefined);
    EnableErrorBarriers: boolean;
    Timeout: int;
    get Transaction(): NpgsqlTransaction | undefined;
    set Transaction(value: NpgsqlTransaction | undefined);
    Cancel(): void;
    CreateBatchCommand(): NpgsqlBatchCommand;
    CreateDbBatchCommand(): DbBatchCommand;
    Dispose(): void;
    ExecuteDbDataReader(behavior: CommandBehavior): DbDataReader;
    ExecuteDbDataReaderAsync(behavior: CommandBehavior, cancellationToken: CancellationToken): Task_1<DbDataReader>;
    ExecuteNonQuery(): int;
    ExecuteNonQueryAsync(cancellationToken?: CancellationToken): Task_1<System_Internal.Int32>;
    ExecuteReader(behavior?: CommandBehavior): NpgsqlDataReader;
    ExecuteReaderAsync(cancellationToken?: CancellationToken): Task_1<NpgsqlDataReader>;
    ExecuteReaderAsync(behavior: CommandBehavior, cancellationToken?: CancellationToken): Task_1<NpgsqlDataReader>;
    ExecuteScalar(): unknown | undefined;
    ExecuteScalarAsync(cancellationToken?: CancellationToken): Task_1<unknown | undefined>;
    Prepare(): void;
    PrepareAsync(cancellationToken?: CancellationToken): Task;
}


export const NpgsqlBatch: {
    new(connection: NpgsqlConnection, transaction: NpgsqlTransaction): NpgsqlBatch;
};


export type NpgsqlBatch = NpgsqlBatch$instance;

export interface NpgsqlBatchCommand$instance extends DbBatchCommand {
    AppendErrorBarrier: Nullable_1<System_Internal.Boolean>;
    readonly CanCreateParameter: boolean;
    CommandText: string;
    CommandType: CommandType;
    readonly DbParameterCollection: DbParameterCollection;
    OID: uint;
    readonly Parameters: NpgsqlParameterCollection;
    readonly RecordsAffected: int;
    Rows: ulong;
    StatementType: StatementType;
    CreateParameter(): NpgsqlParameter;
    ToString(): string;
}


export const NpgsqlBatchCommand: {
    new(): NpgsqlBatchCommand;
    new(commandText: string): NpgsqlBatchCommand;
};


export type NpgsqlBatchCommand = NpgsqlBatchCommand$instance;

export interface NpgsqlBatchCommandCollection$instance extends DbBatchCommandCollection {
    readonly __tsonic_iface_System_Collections_Generic_ICollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IList_1: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;

    readonly Count: int;
    readonly IsReadOnly: boolean;
    [index: number]: NpgsqlBatchCommand;
    Add(item: NpgsqlBatchCommand): void;
    Add(item: DbBatchCommand): void;
    Clear(): void;
    Contains(item: NpgsqlBatchCommand): boolean;
    Contains(item: DbBatchCommand): boolean;
    CopyTo(array: NpgsqlBatchCommand[], arrayIndex: int): void;
    CopyTo(array: DbBatchCommand[], arrayIndex: int): void;
    GetBatchCommand(index: int): DbBatchCommand;
    GetEnumerator(): IEnumerator_1<DbBatchCommand>;
    IndexOf(item: NpgsqlBatchCommand): int;
    IndexOf(item: DbBatchCommand): int;
    Insert(index: int, item: NpgsqlBatchCommand): void;
    Insert(index: int, item: DbBatchCommand): void;
    Remove(item: NpgsqlBatchCommand): boolean;
    Remove(item: DbBatchCommand): boolean;
    RemoveAt(index: int): void;
    SetBatchCommand(index: int, batchCommand: DbBatchCommand): void;
}


export const NpgsqlBatchCommandCollection: {
};


export type NpgsqlBatchCommandCollection = NpgsqlBatchCommandCollection$instance;

export interface NpgsqlBinaryExporter$instance {
    readonly __tsonic_iface_Npgsql_ICancelable: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly IsNull: boolean;
    Timeout: TimeSpan;
    Cancel(): void;
    CancelAsync(): Task;
    Dispose(): void;
    DisposeAsync(): ValueTask;
    Read<T>(): T;
    Read<T>(type: NpgsqlDbType): T;
    ReadAsync<T>(cancellationToken?: CancellationToken): ValueTask_1<T>;
    ReadAsync<T>(type: NpgsqlDbType, cancellationToken?: CancellationToken): ValueTask_1<T>;
    Skip(): void;
    SkipAsync(cancellationToken?: CancellationToken): Task;
    StartRow(): int;
    StartRowAsync(cancellationToken?: CancellationToken): ValueTask_1<System_Internal.Int32>;
}


export const NpgsqlBinaryExporter: {
};


export type NpgsqlBinaryExporter = NpgsqlBinaryExporter$instance;

export interface NpgsqlBinaryImporter$instance {
    readonly __tsonic_iface_Npgsql_ICancelable: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    Timeout: TimeSpan;
    Close(): void;
    CloseAsync(cancellationToken?: CancellationToken): ValueTask;
    Complete(): ulong;
    CompleteAsync(cancellationToken?: CancellationToken): ValueTask_1<System_Internal.UInt64>;
    Dispose(): void;
    DisposeAsync(): ValueTask;
    StartRow(): void;
    StartRowAsync(cancellationToken?: CancellationToken): Task;
    Write<T>(value: T): void;
    Write<T>(value: T, npgsqlDbType: NpgsqlDbType): void;
    Write<T>(value: T, dataTypeName: string): void;
    WriteAsync<T>(value: T, cancellationToken?: CancellationToken): Task;
    WriteAsync<T>(value: T, npgsqlDbType: NpgsqlDbType, cancellationToken?: CancellationToken): Task;
    WriteAsync<T>(value: T, dataTypeName: string, cancellationToken?: CancellationToken): Task;
    WriteNull(): void;
    WriteNullAsync(cancellationToken?: CancellationToken): Task;
    WriteRow(...values: unknown[]): void;
    WriteRowAsync(cancellationToken?: CancellationToken, ...values: unknown[]): Task;
}


export const NpgsqlBinaryImporter: {
};


export type NpgsqlBinaryImporter = NpgsqlBinaryImporter$instance;

export interface NpgsqlCommand$instance extends DbCommand {
    readonly __tsonic_iface_System_ComponentModel_IComponent: never;
    readonly __tsonic_iface_System_Data_IDbCommand: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_ICloneable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    AllResultTypesAreUnknown: boolean;
    CommandText: string;
    CommandTimeout: int;
    CommandType: CommandType;
    get Connection(): NpgsqlConnection | undefined;
    set Connection(value: NpgsqlConnection | undefined);
    get DbConnection(): DbConnection | undefined;
    set DbConnection(value: DbConnection | undefined);
    readonly DbParameterCollection: DbParameterCollection;
    get DbTransaction(): DbTransaction | undefined;
    set DbTransaction(value: DbTransaction | undefined);
    DesignTimeVisible: boolean;
    readonly IsPrepared: boolean;
    readonly Parameters: NpgsqlParameterCollection;
    readonly Statements: IReadOnlyList_1<NpgsqlBatchCommand>;
    get Transaction(): NpgsqlTransaction | undefined;
    set Transaction(value: NpgsqlTransaction | undefined);
    get UnknownResultTypeList(): boolean[] | undefined;
    set UnknownResultTypeList(value: boolean[] | undefined);
    UpdatedRowSource: UpdateRowSource;
    Cancel(): void;
    Clone(): NpgsqlCommand;
    CreateDbParameter(): DbParameter;
    CreateParameter(): NpgsqlParameter;
    Dispose(disposing: boolean): void;
    ExecuteDbDataReader(behavior: CommandBehavior): DbDataReader;
    ExecuteDbDataReaderAsync(behavior: CommandBehavior, cancellationToken: CancellationToken): Task_1<DbDataReader>;
    ExecuteNonQuery(): int;
    ExecuteNonQueryAsync(cancellationToken: CancellationToken): Task_1<System_Internal.Int32>;
    ExecuteReader(behavior?: CommandBehavior): NpgsqlDataReader;
    ExecuteReaderAsync(cancellationToken?: CancellationToken): Task_1<NpgsqlDataReader>;
    ExecuteReaderAsync(behavior: CommandBehavior, cancellationToken?: CancellationToken): Task_1<NpgsqlDataReader>;
    ExecuteScalar(): unknown | undefined;
    ExecuteScalarAsync(cancellationToken: CancellationToken): Task_1<unknown | undefined>;
    Prepare(): void;
    PrepareAsync(cancellationToken?: CancellationToken): Task;
    Unprepare(): void;
    UnprepareAsync(cancellationToken?: CancellationToken): Task;
}


export const NpgsqlCommand: {
    new(): NpgsqlCommand;
    new(cmdText: string): NpgsqlCommand;
    new(cmdText: string, connection: NpgsqlConnection): NpgsqlCommand;
    new(cmdText: string, connection: NpgsqlConnection, transaction: NpgsqlTransaction): NpgsqlCommand;
};


export type NpgsqlCommand = NpgsqlCommand$instance;

export interface NpgsqlCommandBuilder$instance extends DbCommandBuilder {
    readonly __tsonic_iface_System_ComponentModel_IComponent: never;
    readonly __tsonic_iface_System_IDisposable: never;

    QuotePrefix: string;
    QuoteSuffix: string;
    ApplyParameterInfo(p: DbParameter, row: DataRow, statementType: StatementType_Data, whereClause: boolean): void;
    GetDeleteCommand(): NpgsqlCommand;
    GetDeleteCommand(useColumnsForParameterNames: boolean): NpgsqlCommand;
    GetInsertCommand(): NpgsqlCommand;
    GetInsertCommand(useColumnsForParameterNames: boolean): NpgsqlCommand;
    GetParameterName(parameterOrdinal: int): string;
    GetParameterName(parameterName: string): string;
    GetParameterPlaceholder(parameterOrdinal: int): string;
    GetUpdateCommand(): NpgsqlCommand;
    GetUpdateCommand(useColumnsForParameterNames: boolean): NpgsqlCommand;
    QuoteIdentifier(unquotedIdentifier: string): string;
    SetRowUpdatingHandler(adapter: DbDataAdapter): void;
    UnquoteIdentifier(quotedIdentifier: string): string;
}


export const NpgsqlCommandBuilder: {
    new(): NpgsqlCommandBuilder;
    new(adapter: NpgsqlDataAdapter): NpgsqlCommandBuilder;
    DeriveParameters(command: NpgsqlCommand): void;
};


export type NpgsqlCommandBuilder = NpgsqlCommandBuilder$instance;

export interface NpgsqlConnection$instance extends DbConnection {
    readonly __tsonic_iface_System_ComponentModel_IComponent: never;
    readonly __tsonic_iface_System_Data_IDbConnection: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_ICloneable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly CanCreateBatch: boolean;
    readonly CommandTimeout: int;
    ConnectionString: string;
    readonly ConnectionTimeout: int;
    readonly Database: string;
    readonly DataSource: string;
    readonly DbProviderFactory: DbProviderFactory;
    FullState: ConnectionState;
    readonly HasIntegerDateTimes: boolean;
    readonly Host: string | undefined;
    readonly Port: int;
    readonly PostgresParameters: IReadOnlyDictionary_2<System_Internal.String, System_Internal.String>;
    readonly PostgreSqlVersion: Version;
    readonly ProcessID: int;
    get ProvideClientCertificatesCallback(): ProvideClientCertificatesCallback | undefined;
    set ProvideClientCertificatesCallback(value: ProvideClientCertificatesCallback | undefined);
    get ProvidePasswordCallback(): ProvidePasswordCallback | undefined;
    set ProvidePasswordCallback(value: ProvidePasswordCallback | undefined);
    readonly ServerVersion: string;
    get SslClientAuthenticationOptionsCallback(): Action_1<SslClientAuthenticationOptions> | undefined;
    set SslClientAuthenticationOptionsCallback(value: Action_1<SslClientAuthenticationOptions> | undefined);
    readonly State: ConnectionState;
    readonly Timezone: string;
    readonly TypeMapper: INpgsqlTypeMapper;
    get UserCertificateValidationCallback(): RemoteCertificateValidationCallback | undefined;
    set UserCertificateValidationCallback(value: RemoteCertificateValidationCallback | undefined);
    readonly UserName: string | undefined;
    BeginBinaryExport(copyToCommand: string): NpgsqlBinaryExporter;
    BeginBinaryExportAsync(copyToCommand: string, cancellationToken?: CancellationToken): Task_1<NpgsqlBinaryExporter>;
    BeginBinaryImport(copyFromCommand: string): NpgsqlBinaryImporter;
    BeginBinaryImportAsync(copyFromCommand: string, cancellationToken?: CancellationToken): Task_1<NpgsqlBinaryImporter>;
    BeginDbTransaction(isolationLevel: IsolationLevel): DbTransaction;
    BeginDbTransactionAsync(isolationLevel: IsolationLevel, cancellationToken: CancellationToken): ValueTask_1<DbTransaction>;
    BeginRawBinaryCopy(copyCommand: string): NpgsqlRawCopyStream;
    BeginRawBinaryCopyAsync(copyCommand: string, cancellationToken?: CancellationToken): Task_1<NpgsqlRawCopyStream>;
    BeginTextExport(copyToCommand: string): NpgsqlCopyTextReader;
    BeginTextExportAsync(copyToCommand: string, cancellationToken?: CancellationToken): Task_1<NpgsqlCopyTextReader>;
    BeginTextImport(copyFromCommand: string): NpgsqlCopyTextWriter;
    BeginTextImportAsync(copyFromCommand: string, cancellationToken?: CancellationToken): Task_1<NpgsqlCopyTextWriter>;
    BeginTransaction(): NpgsqlTransaction;
    BeginTransaction(level: IsolationLevel): NpgsqlTransaction;
    BeginTransactionAsync(cancellationToken?: CancellationToken): ValueTask_1<NpgsqlTransaction>;
    BeginTransactionAsync(level: IsolationLevel, cancellationToken?: CancellationToken): ValueTask_1<NpgsqlTransaction>;
    ChangeDatabase(dbName: string): void;
    CloneWith(connectionString: string): NpgsqlConnection;
    CloneWithAsync(connectionString: string, cancellationToken?: CancellationToken): ValueTask_1<NpgsqlConnection>;
    Close(): void;
    CloseAsync(): Task;
    CreateBatch(): NpgsqlBatch;
    CreateCommand(): NpgsqlCommand;
    CreateDbBatch(): DbBatch;
    CreateDbCommand(): DbCommand;
    Dispose(disposing: boolean): void;
    DisposeAsync(): ValueTask;
    EnlistTransaction(transaction: Transaction): void;
    GetSchema(): DataTable;
    GetSchema(collectionName: string): DataTable;
    GetSchema(collectionName: string, restrictions: string[]): DataTable;
    GetSchemaAsync(cancellationToken?: CancellationToken): Task_1<DataTable>;
    GetSchemaAsync(collectionName: string, cancellationToken?: CancellationToken): Task_1<DataTable>;
    GetSchemaAsync(collectionName: string, restrictions: string[], cancellationToken?: CancellationToken): Task_1<DataTable>;
    Open(): void;
    OpenAsync(cancellationToken: CancellationToken): Task;
    ReloadTypes(): void;
    ReloadTypesAsync(cancellationToken?: CancellationToken): Task;
    UnprepareAll(): void;
    Wait(timeout: int): boolean;
    Wait(timeout: TimeSpan): boolean;
    Wait(): void;
    WaitAsync(timeout: int, cancellationToken?: CancellationToken): Task_1<System_Internal.Boolean>;
    WaitAsync(timeout: TimeSpan, cancellationToken?: CancellationToken): Task_1<System_Internal.Boolean>;
    WaitAsync(cancellationToken?: CancellationToken): Task;
}


export const NpgsqlConnection: {
    new(): NpgsqlConnection;
    new(connectionString: string): NpgsqlConnection;
    readonly DefaultPort: int;
    readonly GlobalTypeMapper: INpgsqlTypeMapper;
    ClearAllPools(): void;
    ClearPool(connection: NpgsqlConnection): void;
};


export type NpgsqlConnection = NpgsqlConnection$instance;

export interface NpgsqlConnectionStringBuilder$instance extends DbConnectionStringBuilder {
    readonly __tsonic_iface_System_Collections_Generic_ICollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IDictionary_2: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IDictionary: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_ComponentModel_ICustomTypeDescriptor: never;

    get ApplicationName(): string | undefined;
    set ApplicationName(value: string | undefined);
    ArrayNullabilityMode: ArrayNullabilityMode;
    AutoPrepareMinUsages: int;
    CancellationTimeout: int;
    ChannelBinding: ChannelBinding;
    CheckCertificateRevocation: boolean;
    get ClientEncoding(): string | undefined;
    set ClientEncoding(value: string | undefined);
    CommandTimeout: int;
    ConnectionIdleLifetime: int;
    ConnectionLifetime: int;
    ConnectionPruningInterval: int;
    get Database(): string | undefined;
    set Database(value: string | undefined);
    Encoding: string;
    Enlist: boolean;
    GssEncryptionMode: GssEncryptionMode;
    get Host(): string | undefined;
    set Host(value: string | undefined);
    HostRecheckSeconds: int;
    IncludeErrorDetail: boolean;
    IncludeFailedBatchedCommand: boolean;
    IncludeRealm: boolean;
    InternalCommandTimeout: int;
    [keyword: string]: unknown;
    KeepAlive: int;
    KerberosServiceName: string;
    readonly Keys: ICollection_1<System_Internal.String>;
    LoadBalanceHosts: boolean;
    LoadTableComposites: boolean;
    LogParameters: boolean;
    MaxAutoPrepare: int;
    MaxPoolSize: int;
    MinPoolSize: int;
    Multiplexing: boolean;
    NoResetOnClose: boolean;
    get Options(): string | undefined;
    set Options(value: string | undefined);
    get Passfile(): string | undefined;
    set Passfile(value: string | undefined);
    get Password(): string | undefined;
    set Password(value: string | undefined);
    PersistSecurityInfo: boolean;
    Pooling: boolean;
    Port: int;
    ReadBufferSize: int;
    get RequireAuth(): string | undefined;
    set RequireAuth(value: string | undefined);
    get RootCertificate(): string | undefined;
    set RootCertificate(value: string | undefined);
    get SearchPath(): string | undefined;
    set SearchPath(value: string | undefined);
    ServerCompatibilityMode: ServerCompatibilityMode;
    SocketReceiveBufferSize: int;
    SocketSendBufferSize: int;
    get SslCertificate(): string | undefined;
    set SslCertificate(value: string | undefined);
    get SslKey(): string | undefined;
    set SslKey(value: string | undefined);
    SslMode: SslMode;
    SslNegotiation: SslNegotiation;
    get SslPassword(): string | undefined;
    set SslPassword(value: string | undefined);
    get TargetSessionAttributes(): string | undefined;
    set TargetSessionAttributes(value: string | undefined);
    TcpKeepAlive: boolean;
    TcpKeepAliveInterval: int;
    TcpKeepAliveTime: int;
    Timeout: int;
    get Timezone(): string | undefined;
    set Timezone(value: string | undefined);
    TrustServerCertificate: boolean;
    get Username(): string | undefined;
    set Username(value: string | undefined);
    readonly Values: ICollection_1<unknown | undefined>;
    WriteBufferSize: int;
    WriteCoalescingBufferThresholdBytes: int;
    Add(item: KeyValuePair_2<System_Internal.String, unknown>): void;
    Clear(): void;
    Contains(item: KeyValuePair_2<System_Internal.String, unknown>): boolean;
    ContainsKey(keyword: string): boolean;
    CopyTo(array: KeyValuePair_2<System_Internal.String, unknown>[], arrayIndex: int): void;
    Equals(obj: unknown): boolean;
    GetEnumerator(): IEnumerator_1<KeyValuePair_2<System_Internal.String, unknown>>;
    GetHashCode(): int;
    GetProperties(propertyDescriptors: Hashtable): void;
    Remove(keyword: string): boolean;
    Remove(item: KeyValuePair_2<System_Internal.String, unknown>): boolean;
    TryGetValue(keyword: string, value: unknown): boolean;
}


export const NpgsqlConnectionStringBuilder: {
    new(): NpgsqlConnectionStringBuilder;
    new(useOdbcRules: boolean): NpgsqlConnectionStringBuilder;
    new(connectionString: string): NpgsqlConnectionStringBuilder;
};


export type NpgsqlConnectionStringBuilder = NpgsqlConnectionStringBuilder$instance;

export interface NpgsqlCopyTextReader$instance extends StreamReader {
    readonly __tsonic_iface_Npgsql_ICancelable: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    Timeout: int;
    Cancel(): void;
    CancelAsync(): Task;
    DisposeAsync(): ValueTask;
}


export const NpgsqlCopyTextReader: {
};


export type NpgsqlCopyTextReader = NpgsqlCopyTextReader$instance;

export interface NpgsqlCopyTextWriter$instance extends StreamWriter {
    readonly __tsonic_iface_Npgsql_ICancelable: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    Timeout: int;
    Cancel(): void;
    CancelAsync(): Task;
}


export const NpgsqlCopyTextWriter: {
};


export type NpgsqlCopyTextWriter = NpgsqlCopyTextWriter$instance;

export interface NpgsqlDataAdapter$instance extends DbDataAdapter {
    readonly __tsonic_iface_System_ComponentModel_IComponent: never;
    readonly __tsonic_iface_System_Data_IDataAdapter: never;
    readonly __tsonic_iface_System_Data_IDbDataAdapter: never;
    readonly __tsonic_iface_System_ICloneable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    get DeleteCommand(): NpgsqlCommand | undefined;
    set DeleteCommand(value: NpgsqlCommand | undefined);
    get InsertCommand(): NpgsqlCommand | undefined;
    set InsertCommand(value: NpgsqlCommand | undefined);
    get SelectCommand(): NpgsqlCommand | undefined;
    set SelectCommand(value: NpgsqlCommand | undefined);
    get UpdateCommand(): NpgsqlCommand | undefined;
    set UpdateCommand(value: NpgsqlCommand | undefined);
    CreateRowUpdatedEvent(dataRow: DataRow, command: IDbCommand, statementType: StatementType_Data, tableMapping: DataTableMapping): RowUpdatedEventArgs;
    CreateRowUpdatingEvent(dataRow: DataRow, command: IDbCommand, statementType: StatementType_Data, tableMapping: DataTableMapping): RowUpdatingEventArgs;
    OnRowUpdated(value: RowUpdatedEventArgs): void;
    OnRowUpdating(value: RowUpdatingEventArgs): void;
}


export const NpgsqlDataAdapter: {
    new(): NpgsqlDataAdapter;
    new(selectCommand: NpgsqlCommand): NpgsqlDataAdapter;
    new(selectCommandText: string, selectConnection: NpgsqlConnection): NpgsqlDataAdapter;
    new(selectCommandText: string, selectConnectionString: string): NpgsqlDataAdapter;
};


export type NpgsqlDataAdapter = NpgsqlDataAdapter$instance;

export interface NpgsqlDataReader$instance extends DbDataReader {
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Data_Common_IDbColumnSchemaGenerator: never;
    readonly __tsonic_iface_System_Data_IDataReader: never;
    readonly __tsonic_iface_System_Data_IDataRecord: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Depth: int;
    readonly FieldCount: int;
    readonly HasRows: boolean;
    readonly IsClosed: boolean;
    readonly IsOnRow: boolean;
    readonly RecordsAffected: int;
    readonly Rows: ulong;
    readonly Statements: IReadOnlyList_1<NpgsqlBatchCommand>;
    Close(): void;
    CloseAsync(): Task;
    Dispose(disposing: boolean): void;
    DisposeAsync(): ValueTask;
    get_Item(ordinal: int): unknown;
    get_Item(name: string): unknown;
    GetBoolean(ordinal: int): boolean;
    GetByte(ordinal: int): byte;
    GetBytes(ordinal: int, dataOffset: long, buffer: byte[], bufferOffset: int, length: int): long;
    GetChar(ordinal: int): char;
    GetChars(ordinal: int, dataOffset: long, buffer: char[], bufferOffset: int, length: int): long;
    GetColumnSchema(): ReadOnlyCollection_1<NpgsqlDbColumn>;
    GetColumnSchemaAsync(cancellationToken?: CancellationToken): Task_1<ReadOnlyCollection_1<DbColumn>>;
    GetData(ordinal: int): NpgsqlNestedDataReader;
    GetDataTypeName(ordinal: int): string;
    GetDataTypeOID(ordinal: int): uint;
    GetDateTime(ordinal: int): DateTime;
    GetDbDataReader(ordinal: int): DbDataReader;
    GetDecimal(ordinal: int): decimal;
    GetDouble(ordinal: int): double;
    GetEnumerator(): IEnumerator;
    GetFieldType(ordinal: int): Type;
    GetFieldValue<T>(ordinal: int): T;
    GetFieldValueAsync<T>(ordinal: int, cancellationToken: CancellationToken): Task_1<T>;
    GetFloat(ordinal: int): float;
    GetGuid(ordinal: int): Guid;
    GetInt16(ordinal: int): short;
    GetInt32(ordinal: int): int;
    GetInt64(ordinal: int): long;
    GetName(ordinal: int): string;
    GetOrdinal(name: string): int;
    GetPostgresType(ordinal: int): PostgresType;
    GetSchemaTable(): DataTable | undefined;
    GetSchemaTableAsync(cancellationToken?: CancellationToken): Task_1<DataTable | undefined>;
    GetStream(ordinal: int): Stream;
    GetStreamAsync(ordinal: int, cancellationToken?: CancellationToken): Task_1<Stream>;
    GetString(ordinal: int): string;
    GetTextReader(ordinal: int): TextReader;
    GetTextReaderAsync(ordinal: int, cancellationToken?: CancellationToken): Task_1<TextReader>;
    GetTimeSpan(ordinal: int): TimeSpan;
    GetValue(ordinal: int): unknown;
    GetValues(values: unknown[]): int;
    IsDBNull(ordinal: int): boolean;
    IsDBNullAsync(ordinal: int, cancellationToken: CancellationToken): Task_1<System_Internal.Boolean>;
    NextResult(): boolean;
    NextResultAsync(cancellationToken: CancellationToken): Task_1<System_Internal.Boolean>;
    Read(): boolean;
    ReadAsync(cancellationToken: CancellationToken): Task_1<System_Internal.Boolean>;
}


export const NpgsqlDataReader: {
};


export type NpgsqlDataReader = NpgsqlDataReader$instance;

export interface NpgsqlDataSource$instance extends DbDataSource {
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly ConnectionString: string;
    Password: string;
    Clear(): void;
    CreateBatch(): NpgsqlBatch;
    CreateCommand(commandText?: string): NpgsqlCommand;
    CreateConnection(): NpgsqlConnection;
    CreateDbBatch(): DbBatch;
    CreateDbCommand(commandText?: string): DbCommand;
    CreateDbConnection(): DbConnection;
    Dispose(disposing: boolean): void;
    DisposeAsyncBase(): ValueTask;
    DisposeAsyncCore(): ValueTask;
    DisposeBase(): void;
    OpenConnection(): NpgsqlConnection;
    OpenConnectionAsync(cancellationToken?: CancellationToken): ValueTask_1<NpgsqlConnection>;
    OpenDbConnection(): DbConnection;
    OpenDbConnectionAsync(cancellationToken?: CancellationToken): ValueTask_1<DbConnection>;
    ReloadTypes(): void;
    ReloadTypesAsync(cancellationToken?: CancellationToken): Task;
}


export const NpgsqlDataSource: {
    Create(connectionStringBuilder: NpgsqlConnectionStringBuilder): NpgsqlDataSource;
    Create(connectionString: string): NpgsqlDataSource;
};


export type NpgsqlDataSource = NpgsqlDataSource$instance;

export interface NpgsqlDataSourceBuilder$instance {
    readonly __tsonic_iface_Npgsql_TypeMapping_INpgsqlTypeMapper: never;

    readonly ConnectionString: string;
    readonly ConnectionStringBuilder: NpgsqlConnectionStringBuilder;
    DefaultNameTranslator: INpgsqlNameTranslator;
    get Name(): string | undefined;
    set Name(value: string | undefined);
    AddTypeInfoResolverFactory(factory: PgTypeInfoResolverFactory): void;
    Build(): NpgsqlDataSource;
    BuildMultiHost(): NpgsqlMultiHostDataSource;
    ConfigureJsonOptions(serializerOptions: JsonSerializerOptions): NpgsqlDataSourceBuilder;
    ConfigureTracing(configureAction: Action_1<NpgsqlTracingOptionsBuilder>): NpgsqlDataSourceBuilder;
    ConfigureTypeLoading(configureAction: Action_1<NpgsqlTypeLoadingOptionsBuilder>): NpgsqlDataSourceBuilder;
    EnableDynamicJson(jsonbClrTypes?: Type[], jsonClrTypes?: Type[]): NpgsqlDataSourceBuilder;
    EnableParameterLogging(parameterLoggingEnabled?: boolean): NpgsqlDataSourceBuilder;
    EnableRecordsAsTuples(): NpgsqlDataSourceBuilder;
    EnableUnmappedTypes(): NpgsqlDataSourceBuilder;
    MapComposite<T>(pgName?: string, nameTranslator?: INpgsqlNameTranslator): NpgsqlDataSourceBuilder;
    MapComposite(clrType: Type, pgName?: string, nameTranslator?: INpgsqlNameTranslator): NpgsqlDataSourceBuilder;
    MapEnum<TEnum extends number>(pgName?: string, nameTranslator?: INpgsqlNameTranslator): NpgsqlDataSourceBuilder;
    MapEnum(clrType: Type, pgName?: string, nameTranslator?: INpgsqlNameTranslator): NpgsqlDataSourceBuilder;
    UnmapComposite<T>(pgName?: string, nameTranslator?: INpgsqlNameTranslator): boolean;
    UnmapComposite(clrType: Type, pgName?: string, nameTranslator?: INpgsqlNameTranslator): boolean;
    UnmapEnum<TEnum extends number>(pgName?: string, nameTranslator?: INpgsqlNameTranslator): boolean;
    UnmapEnum(clrType: Type, pgName?: string, nameTranslator?: INpgsqlNameTranslator): boolean;
    UseClientCertificate(clientCertificate: X509Certificate): NpgsqlDataSourceBuilder;
    UseClientCertificates(clientCertificates: X509CertificateCollection): NpgsqlDataSourceBuilder;
    UseClientCertificatesCallback(clientCertificatesCallback: Action_1<X509CertificateCollection>): NpgsqlDataSourceBuilder;
    UseLoggerFactory(loggerFactory: ILoggerFactory): NpgsqlDataSourceBuilder;
    UseNegotiateOptionsCallback(negotiateOptionsCallback: Action_1<NegotiateAuthenticationClientOptions>): NpgsqlDataSourceBuilder;
    UsePasswordProvider(passwordProvider: Func_2<NpgsqlConnectionStringBuilder, System_Internal.String>, passwordProviderAsync: Func_3<NpgsqlConnectionStringBuilder, CancellationToken, ValueTask_1<System_Internal.String>>): NpgsqlDataSourceBuilder;
    UsePeriodicPasswordProvider(passwordProvider: Func_3<NpgsqlConnectionStringBuilder, CancellationToken, ValueTask_1<System_Internal.String>>, successRefreshInterval: TimeSpan, failureRefreshInterval: TimeSpan): NpgsqlDataSourceBuilder;
    UsePhysicalConnectionInitializer(connectionInitializer: Action_1<NpgsqlConnection>, connectionInitializerAsync: Func_2<NpgsqlConnection, Task>): NpgsqlDataSourceBuilder;
    UseRootCertificate(rootCertificate: X509Certificate2): NpgsqlDataSourceBuilder;
    UseRootCertificateCallback(rootCertificateCallback: Func_1<X509Certificate2>): NpgsqlDataSourceBuilder;
    UseRootCertificates(rootCertificates: X509Certificate2Collection): NpgsqlDataSourceBuilder;
    UseRootCertificatesCallback(rootCertificateCallback: Func_1<X509Certificate2Collection>): NpgsqlDataSourceBuilder;
    UseSslClientAuthenticationOptionsCallback(sslClientAuthenticationOptionsCallback: Action_1<SslClientAuthenticationOptions>): NpgsqlDataSourceBuilder;
    UseUserCertificateValidationCallback(userCertificateValidationCallback: RemoteCertificateValidationCallback): NpgsqlDataSourceBuilder;
}


export const NpgsqlDataSourceBuilder: {
    new(connectionString: string): NpgsqlDataSourceBuilder;
};


export interface __NpgsqlDataSourceBuilder$views {
    As_INpgsqlTypeMapper(): Npgsql_TypeMapping_Internal.INpgsqlTypeMapper$instance;
}

export type NpgsqlDataSourceBuilder = NpgsqlDataSourceBuilder$instance & __NpgsqlDataSourceBuilder$views;


export interface NpgsqlException$instance extends DbException {
    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    get BatchCommand(): NpgsqlBatchCommand | undefined;
    set BatchCommand(value: NpgsqlBatchCommand | undefined);
    readonly DbBatchCommand: DbBatchCommand | undefined;
    readonly IsTransient: boolean;
}


export const NpgsqlException: {
    new(): NpgsqlException;
    new(message: string, innerException: Exception): NpgsqlException;
    new(message: string): NpgsqlException;
};


export type NpgsqlException = NpgsqlException$instance;

export interface NpgsqlFactory$instance extends DbProviderFactory {
    readonly __tsonic_iface_System_IServiceProvider: never;

    readonly CanCreateBatch: boolean;
    readonly CanCreateCommandBuilder: boolean;
    readonly CanCreateDataAdapter: boolean;
    CreateBatch(): DbBatch;
    CreateBatchCommand(): DbBatchCommand;
    CreateCommand(): DbCommand;
    CreateCommandBuilder(): DbCommandBuilder;
    CreateConnection(): DbConnection;
    CreateConnectionStringBuilder(): DbConnectionStringBuilder;
    CreateDataAdapter(): DbDataAdapter;
    CreateDataSource(connectionString: string): DbDataSource;
    CreateParameter(): DbParameter;
    GetService(serviceType: Type): unknown | undefined;
}


export const NpgsqlFactory: {
    readonly Instance: NpgsqlFactory;
};


export type NpgsqlFactory = NpgsqlFactory$instance;

export interface NpgsqlLargeObjectManager$instance {
    readonly Has64BitSupport: boolean;
    MaxTransferBlockSize: int;
    Create(preferredOid?: uint): uint;
    CreateAsync(preferredOid: uint, cancellationToken?: CancellationToken): Task_1<System_Internal.UInt32>;
    ExportRemote(oid: uint, path: string): void;
    ExportRemoteAsync(oid: uint, path: string, cancellationToken?: CancellationToken): Task;
    ImportRemote(path: string, oid?: uint): void;
    ImportRemoteAsync(path: string, oid: uint, cancellationToken?: CancellationToken): Task;
    OpenRead(oid: uint): NpgsqlLargeObjectStream;
    OpenReadAsync(oid: uint, cancellationToken?: CancellationToken): Task_1<NpgsqlLargeObjectStream>;
    OpenReadWrite(oid: uint): NpgsqlLargeObjectStream;
    OpenReadWriteAsync(oid: uint, cancellationToken?: CancellationToken): Task_1<NpgsqlLargeObjectStream>;
    Unlink(oid: uint): void;
    UnlinkAsync(oid: uint, cancellationToken?: CancellationToken): Task;
}


export const NpgsqlLargeObjectManager: {
    new(connection: NpgsqlConnection): NpgsqlLargeObjectManager;
};


export type NpgsqlLargeObjectManager = NpgsqlLargeObjectManager$instance;

export interface NpgsqlLargeObjectStream$instance extends Stream {
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly CanRead: boolean;
    readonly CanSeek: boolean;
    readonly CanTimeout: boolean;
    readonly CanWrite: boolean;
    readonly Has64BitSupport: boolean;
    readonly Length: long;
    Position: long;
    Close(): void;
    Dispose(disposing: boolean): void;
    Flush(): void;
    GetLengthAsync(cancellationToken?: CancellationToken): Task_1<System_Internal.Int64>;
    Read(buffer: byte[], offset: int, count: int): int;
    ReadAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<System_Internal.Int32>;
    Seek(offset: long, origin: SeekOrigin): long;
    SeekAsync(offset: long, origin: SeekOrigin, cancellationToken?: CancellationToken): Task_1<System_Internal.Int64>;
    SetLength(value: long): void;
    SetLength(value: long, cancellationToken: CancellationToken): Task;
    Write(buffer: byte[], offset: int, count: int): void;
    WriteAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task;
}


export const NpgsqlLargeObjectStream: {
};


export type NpgsqlLargeObjectStream = NpgsqlLargeObjectStream$instance;

export interface NpgsqlLoggingConfiguration$instance {
}


export const NpgsqlLoggingConfiguration: {
    InitializeLogging(loggerFactory: ILoggerFactory, parameterLoggingEnabled?: boolean): void;
};


export type NpgsqlLoggingConfiguration = NpgsqlLoggingConfiguration$instance;

export interface NpgsqlMetricsOptions$instance {
}


export const NpgsqlMetricsOptions: {
    new(): NpgsqlMetricsOptions;
};


export type NpgsqlMetricsOptions = NpgsqlMetricsOptions$instance;

export interface NpgsqlMultiHostDataSource$instance extends NpgsqlDataSource {
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    Clear(): void;
    ClearDatabaseStates(): void;
    CreateConnection(targetSessionAttributes: TargetSessionAttributes): NpgsqlConnection;
    CreateConnection(): NpgsqlConnection;
    OpenConnection(targetSessionAttributes: TargetSessionAttributes): NpgsqlConnection;
    OpenConnection(): NpgsqlConnection;
    OpenConnectionAsync(targetSessionAttributes: TargetSessionAttributes, cancellationToken?: CancellationToken): ValueTask_1<NpgsqlConnection>;
    OpenConnectionAsync(cancellationToken?: CancellationToken): ValueTask_1<NpgsqlConnection>;
    WithTargetSession(targetSessionAttributes: TargetSessionAttributes): NpgsqlDataSource;
}


export const NpgsqlMultiHostDataSource: {
};


export type NpgsqlMultiHostDataSource = NpgsqlMultiHostDataSource$instance;

export interface NpgsqlNestedDataReader$instance extends DbDataReader {
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Data_IDataReader: never;
    readonly __tsonic_iface_System_Data_IDataRecord: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Depth: int;
    readonly FieldCount: int;
    readonly HasRows: boolean;
    readonly IsClosed: boolean;
    readonly RecordsAffected: int;
    Close(): void;
    Dispose(disposing: boolean): void;
    get_Item(ordinal: int): unknown;
    get_Item(name: string): unknown;
    GetBoolean(ordinal: int): boolean;
    GetByte(ordinal: int): byte;
    GetBytes(ordinal: int, dataOffset: long, buffer: byte[], bufferOffset: int, length: int): long;
    GetChar(ordinal: int): char;
    GetChars(ordinal: int, dataOffset: long, buffer: char[], bufferOffset: int, length: int): long;
    GetData(ordinal: int): NpgsqlNestedDataReader;
    GetDataTypeName(ordinal: int): string;
    GetDateTime(ordinal: int): DateTime;
    GetDbDataReader(ordinal: int): DbDataReader;
    GetDecimal(ordinal: int): decimal;
    GetDouble(ordinal: int): double;
    GetEnumerator(): IEnumerator;
    GetFieldType(ordinal: int): Type;
    GetFieldValue<T>(ordinal: int): T;
    GetFloat(ordinal: int): float;
    GetGuid(ordinal: int): Guid;
    GetInt16(ordinal: int): short;
    GetInt32(ordinal: int): int;
    GetInt64(ordinal: int): long;
    GetName(ordinal: int): string;
    GetOrdinal(name: string): int;
    GetString(ordinal: int): string;
    GetValue(ordinal: int): unknown;
    GetValues(values: unknown[]): int;
    IsDBNull(ordinal: int): boolean;
    NextResult(): boolean;
    Read(): boolean;
}


export const NpgsqlNestedDataReader: {
};


export type NpgsqlNestedDataReader = NpgsqlNestedDataReader$instance;

export interface NpgsqlNoticeEventArgs$instance extends EventArgs {
    readonly Notice: PostgresNotice;
}


export const NpgsqlNoticeEventArgs: {
};


export type NpgsqlNoticeEventArgs = NpgsqlNoticeEventArgs$instance;

export interface NpgsqlNotificationEventArgs$instance extends EventArgs {
    readonly Channel: string;
    readonly Payload: string;
    readonly PID: int;
}


export const NpgsqlNotificationEventArgs: {
};


export type NpgsqlNotificationEventArgs = NpgsqlNotificationEventArgs$instance;

export interface NpgsqlOperationInProgressException$instance extends NpgsqlException {
    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly CommandInProgress: NpgsqlCommand | undefined;
}


export const NpgsqlOperationInProgressException: {
    new(command: NpgsqlCommand): NpgsqlOperationInProgressException;
};


export type NpgsqlOperationInProgressException = NpgsqlOperationInProgressException$instance;

export interface NpgsqlParameter$instance extends DbParameter {
    readonly __tsonic_iface_System_Data_IDataParameter: never;
    readonly __tsonic_iface_System_Data_IDbDataParameter: never;
    readonly __tsonic_iface_System_ICloneable: never;

    get Collection(): NpgsqlParameterCollection | undefined;
    set Collection(value: NpgsqlParameterCollection | undefined);
    get DataTypeName(): string | undefined;
    set DataTypeName(value: string | undefined);
    DbType: DbType;
    Direction: ParameterDirection;
    IsNullable: boolean;
    NpgsqlDbType: NpgsqlDbType;
    get NpgsqlValue(): unknown | undefined;
    set NpgsqlValue(value: unknown | undefined);
    ParameterName: string;
    get PostgresType(): PostgresType | undefined;
    set PostgresType(value: PostgresType | undefined);
    Precision: byte;
    Scale: byte;
    Size: int;
    SourceColumn: string;
    SourceColumnNullMapping: boolean;
    SourceVersion: DataRowVersion;
    get Value(): unknown | undefined;
    set Value(value: unknown | undefined);
    Clone(): NpgsqlParameter;
    ResetDbType(): void;
}


export const NpgsqlParameter: {
    new(): NpgsqlParameter;
    new(parameterName: string, value: unknown): NpgsqlParameter;
    new(parameterName: string, parameterType: NpgsqlDbType): NpgsqlParameter;
    new(parameterName: string, parameterType: DbType): NpgsqlParameter;
    new(parameterName: string, parameterType: NpgsqlDbType, size: int): NpgsqlParameter;
    new(parameterName: string, parameterType: DbType, size: int): NpgsqlParameter;
    new(parameterName: string, parameterType: NpgsqlDbType, size: int, sourceColumn: string): NpgsqlParameter;
    new(parameterName: string, parameterType: DbType, size: int, sourceColumn: string): NpgsqlParameter;
    new(parameterName: string, parameterType: NpgsqlDbType, size: int, sourceColumn: string, direction: ParameterDirection, isNullable: boolean, precision: byte, scale: byte, sourceVersion: DataRowVersion, value: unknown): NpgsqlParameter;
    new(parameterName: string, parameterType: DbType, size: int, sourceColumn: string, direction: ParameterDirection, isNullable: boolean, precision: byte, scale: byte, sourceVersion: DataRowVersion, value: unknown): NpgsqlParameter;
};


export type NpgsqlParameter = NpgsqlParameter$instance;

export interface NpgsqlParameter_1$instance<T> extends NpgsqlParameter {
    readonly __tsonic_iface_System_Data_IDataParameter: never;
    readonly __tsonic_iface_System_Data_IDbDataParameter: never;
    readonly __tsonic_iface_System_ICloneable: never;

    TypedValue: T | undefined;
    get Value(): unknown | undefined;
    set Value(value: unknown | undefined);
}


export const NpgsqlParameter_1: {
    new<T>(): NpgsqlParameter_1<T>;
    new<T>(parameterName: string, value: T): NpgsqlParameter_1<T>;
    new<T>(parameterName: string, npgsqlDbType: NpgsqlDbType): NpgsqlParameter_1<T>;
    new<T>(parameterName: string, dbType: DbType): NpgsqlParameter_1<T>;
};


export type NpgsqlParameter_1<T> = NpgsqlParameter_1$instance<T>;

export interface NpgsqlParameterCollection$instance extends DbParameterCollection {
    readonly __tsonic_iface_System_Collections_Generic_ICollection_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IEnumerable_1: never;
    readonly __tsonic_iface_System_Collections_Generic_IList_1: never;
    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_IList: never;
    readonly __tsonic_iface_System_Data_IDataParameterCollection: never;

    readonly Count: int;
    readonly IsFixedSize: boolean;
    readonly IsReadOnly: boolean;
    readonly IsSynchronized: boolean;
    readonly SyncRoot: unknown;
    Add(value: NpgsqlParameter): NpgsqlParameter;
    Add(parameterName: string, parameterType: NpgsqlDbType): NpgsqlParameter;
    Add(parameterName: string, parameterType: NpgsqlDbType, size: int): NpgsqlParameter;
    Add(parameterName: string, parameterType: NpgsqlDbType, size: int, sourceColumn: string): NpgsqlParameter;
    Add(value: unknown): int;
    AddRange(values: ClrArray): void;
    AddWithValue(parameterName: string, value: unknown): NpgsqlParameter;
    AddWithValue(parameterName: string, parameterType: NpgsqlDbType, value: unknown): NpgsqlParameter;
    AddWithValue(parameterName: string, parameterType: NpgsqlDbType, size: int, value: unknown): NpgsqlParameter;
    AddWithValue(parameterName: string, parameterType: NpgsqlDbType, size: int, sourceColumn: string, value: unknown): NpgsqlParameter;
    AddWithValue(value: unknown): NpgsqlParameter;
    AddWithValue(parameterType: NpgsqlDbType, value: unknown): NpgsqlParameter;
    Clear(): void;
    Contains(parameterName: string): boolean;
    Contains(value: unknown): boolean;
    Contains(item: NpgsqlParameter): boolean;
    CopyTo(array: ClrArray, index: int): void;
    CopyTo(array: NpgsqlParameter[], arrayIndex: int): void;
    get_Item(parameterName: string): NpgsqlParameter;
    get_Item(index: int): NpgsqlParameter;
    GetEnumerator(): IEnumerator;
    GetParameter(parameterName: string): DbParameter;
    GetParameter(index: int): DbParameter;
    IndexOf(parameterName: string): int;
    IndexOf(value: unknown): int;
    IndexOf(item: NpgsqlParameter): int;
    Insert(index: int, value: unknown): void;
    Insert(index: int, item: NpgsqlParameter): void;
    Remove(parameterName: string): void;
    Remove(value: unknown): void;
    Remove(item: NpgsqlParameter): boolean;
    RemoveAt(parameterName: string): void;
    RemoveAt(index: int): void;
    set_Item(parameterName: string, value: NpgsqlParameter): void;
    set_Item(index: int, value: NpgsqlParameter): void;
    SetParameter(parameterName: string, value: DbParameter): void;
    SetParameter(index: int, value: DbParameter): void;
    ToArray(): NpgsqlParameter[];
    TryGetValue(parameterName: string, parameter: NpgsqlParameter): boolean;
}


export const NpgsqlParameterCollection: {
};


export type NpgsqlParameterCollection = NpgsqlParameterCollection$instance;

export interface NpgsqlRawCopyStream$instance extends Stream {
    readonly __tsonic_iface_Npgsql_ICancelable: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly CanRead: boolean;
    readonly CanSeek: boolean;
    readonly CanTimeout: boolean;
    readonly CanWrite: boolean;
    readonly Length: long;
    Position: long;
    ReadTimeout: int;
    WriteTimeout: int;
    Cancel(): void;
    CancelAsync(): Task;
    Dispose(disposing: boolean): void;
    DisposeAsync(): ValueTask;
    Flush(): void;
    FlushAsync(cancellationToken: CancellationToken): Task;
    Read(buffer: byte[], offset: int, count: int): int;
    Read(span: Span_1<System_Internal.Byte>): int;
    ReadAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task_1<System_Internal.Int32>;
    ReadAsync(buffer: Memory_1<System_Internal.Byte>, cancellationToken: CancellationToken): ValueTask_1<System_Internal.Int32>;
    Seek(offset: long, origin: SeekOrigin): long;
    SetLength(value: long): void;
    Write(buffer: byte[], offset: int, count: int): void;
    Write(buffer: ReadOnlySpan_1<System_Internal.Byte>): void;
    WriteAsync(buffer: byte[], offset: int, count: int, cancellationToken: CancellationToken): Task;
    WriteAsync(buffer: ReadOnlyMemory_1<System_Internal.Byte>, cancellationToken?: CancellationToken): ValueTask;
}


export const NpgsqlRawCopyStream: {
};


export type NpgsqlRawCopyStream = NpgsqlRawCopyStream$instance;

export interface NpgsqlRowUpdatedEventArgs$instance extends RowUpdatedEventArgs {
}


export const NpgsqlRowUpdatedEventArgs: {
    new(dataRow: DataRow, command: IDbCommand, statementType: StatementType_Data, tableMapping: DataTableMapping): NpgsqlRowUpdatedEventArgs;
};


export type NpgsqlRowUpdatedEventArgs = NpgsqlRowUpdatedEventArgs$instance;

export interface NpgsqlRowUpdatingEventArgs$instance extends RowUpdatingEventArgs {
}


export const NpgsqlRowUpdatingEventArgs: {
    new(dataRow: DataRow, command: IDbCommand, statementType: StatementType_Data, tableMapping: DataTableMapping): NpgsqlRowUpdatingEventArgs;
};


export type NpgsqlRowUpdatingEventArgs = NpgsqlRowUpdatingEventArgs$instance;

export interface NpgsqlSlimDataSourceBuilder$instance {
    readonly __tsonic_iface_Npgsql_TypeMapping_INpgsqlTypeMapper: never;

    readonly ConnectionString: string;
    readonly ConnectionStringBuilder: NpgsqlConnectionStringBuilder;
    DefaultNameTranslator: INpgsqlNameTranslator;
    get Name(): string | undefined;
    set Name(value: string | undefined);
    AddTypeInfoResolverFactory(factory: PgTypeInfoResolverFactory): void;
    Build(): NpgsqlDataSource;
    BuildMultiHost(): NpgsqlMultiHostDataSource;
    ConfigureJsonOptions(serializerOptions: JsonSerializerOptions): NpgsqlSlimDataSourceBuilder;
    ConfigureTracing(configureAction: Action_1<NpgsqlTracingOptionsBuilder>): NpgsqlSlimDataSourceBuilder;
    ConfigureTypeLoading(configureAction: Action_1<NpgsqlTypeLoadingOptionsBuilder>): NpgsqlSlimDataSourceBuilder;
    EnableArrays(): NpgsqlSlimDataSourceBuilder;
    EnableCube(): NpgsqlSlimDataSourceBuilder;
    EnableDynamicJson(jsonbClrTypes?: Type[], jsonClrTypes?: Type[]): NpgsqlSlimDataSourceBuilder;
    EnableExtraConversions(): NpgsqlSlimDataSourceBuilder;
    EnableFullTextSearch(): NpgsqlSlimDataSourceBuilder;
    EnableGeometricTypes(): NpgsqlSlimDataSourceBuilder;
    EnableIntegratedSecurity(): NpgsqlSlimDataSourceBuilder;
    EnableJsonTypes(): NpgsqlSlimDataSourceBuilder;
    EnableLTree(): NpgsqlSlimDataSourceBuilder;
    EnableMultiranges(): NpgsqlSlimDataSourceBuilder;
    EnableNetworkTypes(): NpgsqlSlimDataSourceBuilder;
    EnableParameterLogging(parameterLoggingEnabled?: boolean): NpgsqlSlimDataSourceBuilder;
    EnableRanges(): NpgsqlSlimDataSourceBuilder;
    EnableRecords(): NpgsqlSlimDataSourceBuilder;
    EnableRecordsAsTuples(): NpgsqlSlimDataSourceBuilder;
    EnableTransportSecurity(): NpgsqlSlimDataSourceBuilder;
    EnableUnmappedTypes(): NpgsqlSlimDataSourceBuilder;
    MapComposite<T>(pgName?: string, nameTranslator?: INpgsqlNameTranslator): NpgsqlSlimDataSourceBuilder;
    MapComposite(clrType: Type, pgName?: string, nameTranslator?: INpgsqlNameTranslator): NpgsqlSlimDataSourceBuilder;
    MapEnum<TEnum extends number>(pgName?: string, nameTranslator?: INpgsqlNameTranslator): NpgsqlSlimDataSourceBuilder;
    MapEnum(clrType: Type, pgName?: string, nameTranslator?: INpgsqlNameTranslator): NpgsqlSlimDataSourceBuilder;
    UnmapComposite<T>(pgName?: string, nameTranslator?: INpgsqlNameTranslator): boolean;
    UnmapComposite(clrType: Type, pgName?: string, nameTranslator?: INpgsqlNameTranslator): boolean;
    UnmapEnum<TEnum extends number>(pgName?: string, nameTranslator?: INpgsqlNameTranslator): boolean;
    UnmapEnum(clrType: Type, pgName?: string, nameTranslator?: INpgsqlNameTranslator): boolean;
    UseClientCertificate(clientCertificate: X509Certificate): NpgsqlSlimDataSourceBuilder;
    UseClientCertificates(clientCertificates: X509CertificateCollection): NpgsqlSlimDataSourceBuilder;
    UseClientCertificatesCallback(clientCertificatesCallback: Action_1<X509CertificateCollection>): NpgsqlSlimDataSourceBuilder;
    UseLoggerFactory(loggerFactory: ILoggerFactory): NpgsqlSlimDataSourceBuilder;
    UseNegotiateOptionsCallback(negotiateOptionsCallback: Action_1<NegotiateAuthenticationClientOptions>): NpgsqlSlimDataSourceBuilder;
    UsePasswordProvider(passwordProvider: Func_2<NpgsqlConnectionStringBuilder, System_Internal.String>, passwordProviderAsync: Func_3<NpgsqlConnectionStringBuilder, CancellationToken, ValueTask_1<System_Internal.String>>): NpgsqlSlimDataSourceBuilder;
    UsePeriodicPasswordProvider(passwordProvider: Func_3<NpgsqlConnectionStringBuilder, CancellationToken, ValueTask_1<System_Internal.String>>, successRefreshInterval: TimeSpan, failureRefreshInterval: TimeSpan): NpgsqlSlimDataSourceBuilder;
    UsePhysicalConnectionInitializer(connectionInitializer: Action_1<NpgsqlConnection>, connectionInitializerAsync: Func_2<NpgsqlConnection, Task>): NpgsqlSlimDataSourceBuilder;
    UseRootCertificate(rootCertificate: X509Certificate2): NpgsqlSlimDataSourceBuilder;
    UseRootCertificateCallback(rootCertificateCallback: Func_1<X509Certificate2>): NpgsqlSlimDataSourceBuilder;
    UseRootCertificates(rootCertificates: X509Certificate2Collection): NpgsqlSlimDataSourceBuilder;
    UseRootCertificatesCallback(rootCertificateCallback: Func_1<X509Certificate2Collection>): NpgsqlSlimDataSourceBuilder;
    UseSslClientAuthenticationOptionsCallback(sslClientAuthenticationOptionsCallback: Action_1<SslClientAuthenticationOptions>): NpgsqlSlimDataSourceBuilder;
    UseUserCertificateValidationCallback(userCertificateValidationCallback: RemoteCertificateValidationCallback): NpgsqlSlimDataSourceBuilder;
}


export const NpgsqlSlimDataSourceBuilder: {
    new(connectionString: string): NpgsqlSlimDataSourceBuilder;
};


export interface __NpgsqlSlimDataSourceBuilder$views {
    As_INpgsqlTypeMapper(): Npgsql_TypeMapping_Internal.INpgsqlTypeMapper$instance;
}

export type NpgsqlSlimDataSourceBuilder = NpgsqlSlimDataSourceBuilder$instance & __NpgsqlSlimDataSourceBuilder$views;


export interface NpgsqlTracingOptionsBuilder$instance {
    ConfigureBatchEnrichmentCallback(batchEnrichmentCallback: Action_2<Activity, NpgsqlBatch>): NpgsqlTracingOptionsBuilder;
    ConfigureBatchFilter(batchFilter: Func_2<NpgsqlBatch, System_Internal.Boolean>): NpgsqlTracingOptionsBuilder;
    ConfigureBatchSpanNameProvider(batchSpanNameProvider: Func_2<NpgsqlBatch, System_Internal.String>): NpgsqlTracingOptionsBuilder;
    ConfigureCommandEnrichmentCallback(commandEnrichmentCallback: Action_2<Activity, NpgsqlCommand>): NpgsqlTracingOptionsBuilder;
    ConfigureCommandFilter(commandFilter: Func_2<NpgsqlCommand, System_Internal.Boolean>): NpgsqlTracingOptionsBuilder;
    ConfigureCommandSpanNameProvider(commandSpanNameProvider: Func_2<NpgsqlCommand, System_Internal.String>): NpgsqlTracingOptionsBuilder;
    ConfigureCopyOperationEnrichmentCallback(copyOperationEnrichmentCallback: Action_2<Activity, System_Internal.String>): NpgsqlTracingOptionsBuilder;
    ConfigureCopyOperationFilter(copyOperationFilter: Func_2<System_Internal.String, System_Internal.Boolean>): NpgsqlTracingOptionsBuilder;
    ConfigureCopyOperationSpanNameProvider(copyOperationSpanNameProvider: Func_2<System_Internal.String, System_Internal.String>): NpgsqlTracingOptionsBuilder;
    EnableFirstResponseEvent(enable?: boolean): NpgsqlTracingOptionsBuilder;
    EnablePhysicalOpenTracing(enable?: boolean): NpgsqlTracingOptionsBuilder;
}


export const NpgsqlTracingOptionsBuilder: {
};


export type NpgsqlTracingOptionsBuilder = NpgsqlTracingOptionsBuilder$instance;

export interface NpgsqlTransaction$instance extends DbTransaction {
    readonly __tsonic_iface_System_Data_IDbTransaction: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Connection: NpgsqlConnection | undefined;
    readonly DbConnection: DbConnection | undefined;
    readonly IsolationLevel: IsolationLevel;
    readonly SupportsSavepoints: boolean;
    Commit(): void;
    CommitAsync(cancellationToken?: CancellationToken): Task;
    Dispose(disposing: boolean): void;
    DisposeAsync(): ValueTask;
    Release(name: string): void;
    ReleaseAsync(name: string, cancellationToken?: CancellationToken): Task;
    Rollback(): void;
    Rollback(name: string): void;
    RollbackAsync(cancellationToken?: CancellationToken): Task;
    RollbackAsync(name: string, cancellationToken?: CancellationToken): Task;
    Save(name: string): void;
    SaveAsync(name: string, cancellationToken?: CancellationToken): Task;
}


export const NpgsqlTransaction: {
};


export type NpgsqlTransaction = NpgsqlTransaction$instance;

export interface NpgsqlTypeLoadingOptionsBuilder$instance {
    EnableTableCompositesLoading(enable?: boolean): NpgsqlTypeLoadingOptionsBuilder;
    EnableTypeLoading(enable?: boolean): NpgsqlTypeLoadingOptionsBuilder;
    SetTypeLoadingSchemas(schemas: IEnumerable_1<System_Internal.String>): NpgsqlTypeLoadingOptionsBuilder;
}


export const NpgsqlTypeLoadingOptionsBuilder: {
};


export type NpgsqlTypeLoadingOptionsBuilder = NpgsqlTypeLoadingOptionsBuilder$instance;

export interface PostgresException$instance extends NpgsqlException {
    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly ColumnName: string | undefined;
    readonly ConstraintName: string | undefined;
    readonly DataTypeName: string | undefined;
    readonly Detail: string | undefined;
    readonly File: string | undefined;
    readonly Hint: string | undefined;
    readonly InternalPosition: int;
    readonly InternalQuery: string | undefined;
    readonly InvariantSeverity: string;
    readonly IsTransient: boolean;
    readonly Line: string | undefined;
    readonly MessageText: string;
    readonly Position: int;
    readonly Routine: string | undefined;
    readonly SchemaName: string | undefined;
    readonly Severity: string;
    readonly SqlState: string;
    readonly TableName: string | undefined;
    readonly Where: string | undefined;
    GetObjectData(info: SerializationInfo, context: StreamingContext): void;
    ToString(): string;
}


export const PostgresException: {
    new(messageText: string, severity: string, invariantSeverity: string, sqlState: string): PostgresException;
    new(messageText: string, severity: string, invariantSeverity: string, sqlState: string, detail: string, hint: string, position: int, internalPosition: int, internalQuery: string, where: string, schemaName: string, tableName: string, columnName: string, dataTypeName: string, constraintName: string, file: string, line: string, routine: string): PostgresException;
};


export type PostgresException = PostgresException$instance;

export interface PostgresNotice$instance {
    get ColumnName(): string | undefined;
    set ColumnName(value: string | undefined);
    get ConstraintName(): string | undefined;
    set ConstraintName(value: string | undefined);
    get DataTypeName(): string | undefined;
    set DataTypeName(value: string | undefined);
    get Detail(): string | undefined;
    set Detail(value: string | undefined);
    get File(): string | undefined;
    set File(value: string | undefined);
    get Hint(): string | undefined;
    set Hint(value: string | undefined);
    InternalPosition: int;
    get InternalQuery(): string | undefined;
    set InternalQuery(value: string | undefined);
    readonly InvariantSeverity: string;
    get Line(): string | undefined;
    set Line(value: string | undefined);
    MessageText: string;
    Position: int;
    get Routine(): string | undefined;
    set Routine(value: string | undefined);
    get SchemaName(): string | undefined;
    set SchemaName(value: string | undefined);
    Severity: string;
    SqlState: string;
    get TableName(): string | undefined;
    set TableName(value: string | undefined);
    get Where(): string | undefined;
    set Where(value: string | undefined);
}


export const PostgresNotice: {
    new(severity: string, invariantSeverity: string, sqlState: string, messageText: string): PostgresNotice;
    new(messageText: string, severity: string, invariantSeverity: string, sqlState: string, detail: string, hint: string, position: int, internalPosition: int, internalQuery: string, where: string, schemaName: string, tableName: string, columnName: string, dataTypeName: string, constraintName: string, file: string, line: string, routine: string): PostgresNotice;
};


export type PostgresNotice = PostgresNotice$instance;

export abstract class NpgsqlEventId$instance {
    static readonly OpeningConnection: int;
    static readonly OpenedConnection: int;
    static readonly ClosingConnection: int;
    static readonly ClosedConnection: int;
    static readonly OpeningPhysicalConnection: int;
    static readonly OpenedPhysicalConnection: int;
    static readonly ClosingPhysicalConnection: int;
    static readonly ClosedPhysicalConnection: int;
    static readonly StartingWait: int;
    static readonly ReceivedNotice: int;
    static readonly ConnectionExceededMaximumLifetime: int;
    static readonly SendingKeepalive: int;
    static readonly CompletedKeepalive: int;
    static readonly KeepaliveFailed: int;
    static readonly BreakingConnection: int;
    static readonly CaughtUserExceptionInNoticeEventHandler: int;
    static readonly CaughtUserExceptionInNotificationEventHandler: int;
    static readonly ExceptionWhenClosingPhysicalConnection: int;
    static readonly ExceptionWhenOpeningConnectionForMultiplexing: int;
    static readonly ExecutingCommand: int;
    static readonly CommandExecutionCompleted: int;
    static readonly CancellingCommand: int;
    static readonly ExecutingInternalCommand: int;
    static readonly PreparingCommandExplicitly: int;
    static readonly CommandPreparedExplicitly: int;
    static readonly AutoPreparingStatement: int;
    static readonly UnpreparingCommand: int;
    static readonly DerivingParameters: int;
    static readonly ExceptionWhenWritingMultiplexedCommands: int;
    static readonly StartedTransaction: int;
    static readonly CommittedTransaction: int;
    static readonly RolledBackTransaction: int;
    static readonly CreatingSavepoint: int;
    static readonly RolledBackToSavepoint: int;
    static readonly ReleasedSavepoint: int;
    static readonly ExceptionDuringTransactionDispose: int;
    static readonly EnlistedVolatileResourceManager: int;
    static readonly CommittingSinglePhaseTransaction: int;
    static readonly RollingBackSinglePhaseTransaction: int;
    static readonly SinglePhaseTransactionRollbackFailed: int;
    static readonly PreparingTwoPhaseTransaction: int;
    static readonly CommittingTwoPhaseTransaction: int;
    static readonly TwoPhaseTransactionCommitFailed: int;
    static readonly RollingBackTwoPhaseTransaction: int;
    static readonly TwoPhaseTransactionRollbackFailed: int;
    static readonly TwoPhaseTransactionInDoubt: int;
    static readonly ConnectionInUseWhenRollingBack: int;
    static readonly CleaningUpResourceManager: int;
    static readonly StartingBinaryExport: int;
    static readonly StartingBinaryImport: int;
    static readonly StartingTextExport: int;
    static readonly StartingTextImport: int;
    static readonly StartingRawCopy: int;
    static readonly CopyOperationCompleted: int;
    static readonly CopyOperationCancelled: int;
    static readonly ExceptionWhenDisposingCopyOperation: int;
    static readonly CreatingReplicationSlot: int;
    static readonly DroppingReplicationSlot: int;
    static readonly StartingLogicalReplication: int;
    static readonly StartingPhysicalReplication: int;
    static readonly ExecutingReplicationCommand: int;
    static readonly ReceivedReplicationPrimaryKeepalive: int;
    static readonly SendingReplicationStandbyStatusUpdate: int;
    static readonly SentReplicationFeedbackMessage: int;
    static readonly ReplicationFeedbackMessageSendingFailed: int;
}


export type NpgsqlEventId = NpgsqlEventId$instance;

export abstract class PostgresErrorCodes$instance {
    static readonly SuccessfulCompletion: string;
    static readonly Warning: string;
    static readonly DynamicResultSetsReturnedWarning: string;
    static readonly ImplicitZeroBitPaddingWarning: string;
    static readonly NullValueEliminatedInSetFunctionWarning: string;
    static readonly PrivilegeNotGrantedWarning: string;
    static readonly PrivilegeNotRevokedWarning: string;
    static readonly StringDataRightTruncationWarning: string;
    static readonly DeprecatedFeatureWarning: string;
    static readonly NoData: string;
    static readonly NoAdditionalDynamicResultSetsReturned: string;
    static readonly SqlStatementNotYetComplete: string;
    static readonly ConnectionException: string;
    static readonly ConnectionDoesNotExist: string;
    static readonly ConnectionFailure: string;
    static readonly SqlClientUnableToEstablishSqlConnection: string;
    static readonly SqlServerRejectedEstablishmentOfSqlConnection: string;
    static readonly TransactionResolutionUnknown: string;
    static readonly ProtocolViolation: string;
    static readonly TriggeredActionException: string;
    static readonly FeatureNotSupported: string;
    static readonly InvalidTransactionInitiation: string;
    static readonly LocatorException: string;
    static readonly InvalidLocatorSpecification: string;
    static readonly InvalidGrantor: string;
    static readonly InvalidGrantOperation: string;
    static readonly InvalidRoleSpecification: string;
    static readonly DiagnosticsException: string;
    static readonly StackedDiagnosticsAccessedWithoutActiveHandler: string;
    static readonly CaseNotFound: string;
    static readonly CardinalityViolation: string;
    static readonly DataException: string;
    static readonly ArraySubscriptError: string;
    static readonly CharacterNotInRepertoire: string;
    static readonly DatetimeFieldOverflow: string;
    static readonly DivisionByZero: string;
    static readonly ErrorInAssignment: string;
    static readonly EscapeCharacterConflict: string;
    static readonly IndicatorOverflow: string;
    static readonly IntervalFieldOverflow: string;
    static readonly InvalidArgumentForLogarithm: string;
    static readonly InvalidArgumentForNtileFunction: string;
    static readonly InvalidArgumentForNthValueFunction: string;
    static readonly InvalidArgumentForPowerFunction: string;
    static readonly InvalidArgumentForWidthBucketFunction: string;
    static readonly InvalidCharacterValueForCast: string;
    static readonly InvalidDatetimeFormat: string;
    static readonly InvalidEscapeCharacter: string;
    static readonly InvalidEscapeOctet: string;
    static readonly InvalidEscapeSequence: string;
    static readonly NonstandardUseOfEscapeCharacter: string;
    static readonly InvalidIndicatorParameterValue: string;
    static readonly InvalidParameterValue: string;
    static readonly InvalidRegularExpression: string;
    static readonly InvalidRowCountInLimitClause: string;
    static readonly InvalidRowCountInResultOffsetClause: string;
    static readonly InvalidTablesampleArgument: string;
    static readonly InvalidTablesampleRepeat: string;
    static readonly InvalidTimeZoneDisplacementValue: string;
    static readonly InvalidUseOfEscapeCharacter: string;
    static readonly MostSpecificTypeMismatch: string;
    static readonly NullValueNotAllowed: string;
    static readonly NullValueNoIndicatorParameter: string;
    static readonly NumericValueOutOfRange: string;
    static readonly StringDataLengthMismatch: string;
    static readonly StringDataRightTruncation: string;
    static readonly SubstringError: string;
    static readonly TrimError: string;
    static readonly UnterminatedCString: string;
    static readonly ZeroLengthCharacterString: string;
    static readonly FloatingPointException: string;
    static readonly InvalidTextRepresentation: string;
    static readonly InvalidBinaryRepresentation: string;
    static readonly BadCopyFileFormat: string;
    static readonly UntranslatableCharacter: string;
    static readonly NotAnXmlDocument: string;
    static readonly InvalidXmlDocument: string;
    static readonly InvalidXmlContent: string;
    static readonly InvalidXmlComment: string;
    static readonly InvalidXmlProcessingInstruction: string;
    static readonly IntegrityConstraintViolation: string;
    static readonly RestrictViolation: string;
    static readonly NotNullViolation: string;
    static readonly ForeignKeyViolation: string;
    static readonly UniqueViolation: string;
    static readonly CheckViolation: string;
    static readonly ExclusionViolation: string;
    static readonly InvalidCursorState: string;
    static readonly InvalidTransactionState: string;
    static readonly ActiveSqlTransaction: string;
    static readonly BranchTransactionAlreadyActive: string;
    static readonly HeldCursorRequiresSameIsolationLevel: string;
    static readonly InappropriateAccessModeForBranchTransaction: string;
    static readonly InappropriateIsolationLevelForBranchTransaction: string;
    static readonly NoActiveSqlTransactionForBranchTransaction: string;
    static readonly ReadOnlySqlTransaction: string;
    static readonly SchemaAndDataStatementMixingNotSupported: string;
    static readonly NoActiveSqlTransaction: string;
    static readonly InFailedSqlTransaction: string;
    static readonly InvalidSqlStatementName: string;
    static readonly TriggeredDataChangeViolation: string;
    static readonly InvalidAuthorizationSpecification: string;
    static readonly InvalidPassword: string;
    static readonly DependentPrivilegeDescriptorsStillExist: string;
    static readonly DependentObjectsStillExist: string;
    static readonly InvalidTransactionTermination: string;
    static readonly SqlRoutineException: string;
    static readonly FunctionExecutedNoReturnStatementSqlRoutineException: string;
    static readonly ModifyingSqlDataNotPermittedSqlRoutineException: string;
    static readonly ProhibitedSqlStatementAttemptedSqlRoutineException: string;
    static readonly ReadingSqlDataNotPermittedSqlRoutineException: string;
    static readonly InvalidCursorName: string;
    static readonly ExternalRoutineException: string;
    static readonly ContainingSqlNotPermittedExternalRoutineException: string;
    static readonly ModifyingSqlDataNotPermittedExternalRoutineException: string;
    static readonly ProhibitedSqlStatementAttemptedExternalRoutineException: string;
    static readonly ReadingSqlDataNotPermittedExternalRoutineException: string;
    static readonly ExternalRoutineInvocationException: string;
    static readonly InvalidSqlstateReturnedExternalRoutineInvocationException: string;
    static readonly NullValueNotAllowedExternalRoutineInvocationException: string;
    static readonly TriggerProtocolViolatedExternalRoutineInvocationException: string;
    static readonly SrfProtocolViolatedExternalRoutineInvocationException: string;
    static readonly EventTriggerProtocolViolatedExternalRoutineInvocationException: string;
    static readonly SavepointException: string;
    static readonly InvalidSavepointSpecification: string;
    static readonly InvalidCatalogName: string;
    static readonly InvalidSchemaName: string;
    static readonly TransactionRollback: string;
    static readonly TransactionIntegrityConstraintViolation: string;
    static readonly SerializationFailure: string;
    static readonly StatementCompletionUnknown: string;
    static readonly DeadlockDetected: string;
    static readonly SyntaxErrorOrAccessRuleViolation: string;
    static readonly SyntaxError: string;
    static readonly InsufficientPrivilege: string;
    static readonly CannotCoerce: string;
    static readonly GroupingError: string;
    static readonly WindowingError: string;
    static readonly InvalidRecursion: string;
    static readonly InvalidForeignKey: string;
    static readonly InvalidName: string;
    static readonly NameTooLong: string;
    static readonly ReservedName: string;
    static readonly DatatypeMismatch: string;
    static readonly IndeterminateDatatype: string;
    static readonly CollationMismatch: string;
    static readonly IndeterminateCollation: string;
    static readonly WrongObjectType: string;
    static readonly UndefinedColumn: string;
    static readonly UndefinedFunction: string;
    static readonly UndefinedTable: string;
    static readonly UndefinedParameter: string;
    static readonly UndefinedObject: string;
    static readonly DuplicateColumn: string;
    static readonly DuplicateCursor: string;
    static readonly DuplicateDatabase: string;
    static readonly DuplicateFunction: string;
    static readonly DuplicatePreparedStatement: string;
    static readonly DuplicateSchema: string;
    static readonly DuplicateTable: string;
    static readonly DuplicateAlias: string;
    static readonly DuplicateObject: string;
    static readonly AmbiguousColumn: string;
    static readonly AmbiguousFunction: string;
    static readonly AmbiguousParameter: string;
    static readonly AmbiguousAlias: string;
    static readonly InvalidColumnReference: string;
    static readonly InvalidColumnDefinition: string;
    static readonly InvalidCursorDefinition: string;
    static readonly InvalidDatabaseDefinition: string;
    static readonly InvalidFunctionDefinition: string;
    static readonly InvalidPreparedStatementDefinition: string;
    static readonly InvalidSchemaDefinition: string;
    static readonly InvalidTableDefinition: string;
    static readonly InvalidObjectDefinition: string;
    static readonly WithCheckOptionViolation: string;
    static readonly InsufficientResources: string;
    static readonly DiskFull: string;
    static readonly OutOfMemory: string;
    static readonly TooManyConnections: string;
    static readonly ConfigurationLimitExceeded: string;
    static readonly ProgramLimitExceeded: string;
    static readonly StatementTooComplex: string;
    static readonly TooManyColumns: string;
    static readonly TooManyArguments: string;
    static readonly ObjectNotInPrerequisiteState: string;
    static readonly ObjectInUse: string;
    static readonly CantChangeRuntimeParam: string;
    static readonly LockNotAvailable: string;
    static readonly OperatorIntervention: string;
    static readonly QueryCanceled: string;
    static readonly AdminShutdown: string;
    static readonly CrashShutdown: string;
    static readonly CannotConnectNow: string;
    static readonly DatabaseDropped: string;
    static readonly IdleSessionTimeout: string;
    static readonly SystemError: string;
    static readonly IoError: string;
    static readonly UndefinedFile: string;
    static readonly DuplicateFile: string;
    static readonly SnapshotFailure: string;
    static readonly ConfigFileError: string;
    static readonly LockFileExists: string;
    static readonly FdwError: string;
    static readonly FdwColumnNameNotFound: string;
    static readonly FdwDynamicParameterValueNeeded: string;
    static readonly FdwFunctionSequenceError: string;
    static readonly FdwInconsistentDescriptorInformation: string;
    static readonly FdwInvalidAttributeValue: string;
    static readonly FdwInvalidColumnName: string;
    static readonly FdwInvalidColumnNumber: string;
    static readonly FdwInvalidDataType: string;
    static readonly FdwInvalidDataTypeDescriptors: string;
    static readonly FdwInvalidDescriptorFieldIdentifier: string;
    static readonly FdwInvalidHandle: string;
    static readonly FdwInvalidOptionIndex: string;
    static readonly FdwInvalidOptionName: string;
    static readonly FdwInvalidStringLengthOrBufferLength: string;
    static readonly FdwInvalidStringFormat: string;
    static readonly FdwInvalidUseOfNullPointer: string;
    static readonly FdwTooManyHandles: string;
    static readonly FdwOutOfMemory: string;
    static readonly FdwNoSchemas: string;
    static readonly FdwOptionNameNotFound: string;
    static readonly FdwReplyHandle: string;
    static readonly FdwSchemaNotFound: string;
    static readonly FdwTableNotFound: string;
    static readonly FdwUnableToCreateExecution: string;
    static readonly FdwUnableToCreateReply: string;
    static readonly FdwUnableToEstablishConnection: string;
    static readonly PlpgsqlError: string;
    static readonly RaiseException: string;
    static readonly NoDataFound: string;
    static readonly TooManyRows: string;
    static readonly AssertFailure: string;
    static readonly InternalError: string;
    static readonly DataCorrupted: string;
    static readonly IndexCorrupted: string;
}


export type PostgresErrorCodes = PostgresErrorCodes$instance;

