// Generated by tsbindgen - Architecture
// Namespace: Npgsql.Replication.PgOutput
// Assembly: Npgsql

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { PostgresType } from "../../Npgsql.PostgresTypes/internal/index.js";
import * as Npgsql_Replication_Internal_Internal from "../../Npgsql.Replication.Internal/internal/index.js";
import type { LogicalReplicationSlot } from "../../Npgsql.Replication.Internal/internal/index.js";
import type { ReplicationSlotOptions } from "../../Npgsql.Replication/internal/index.js";
import type { NpgsqlLogSequenceNumber } from "../../NpgsqlTypes/internal/index.js";
import * as System_Collections_Generic_Internal from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { IAsyncEnumerable_1, IAsyncEnumerator_1, IEnumerable_1, List_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { Stream, TextReader } from "@tsonic/dotnet/System.IO/internal/index.js";
import type { ValueTask_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Byte, Enum, IComparable, IConvertible, IEquatable_1, IFormattable, Int32, ISpanFormattable, Nullable_1, Object as ClrObject, String as ClrString, Type, UInt16, UInt64 } from "@tsonic/dotnet/System/internal/index.js";

export enum PgOutputProtocolVersion {
    V1 = 1,
    V2 = 2,
    V3 = 3,
    V4 = 4
}


export enum PgOutputStreamingMode {
    Off = 0,
    On = 1,
    Parallel = 2
}


export enum TupleDataKind {
    Null = 110,
    UnchangedToastedValue = 117,
    TextValue = 116,
    BinaryValue = 98
}


export interface PgOutputReplicationOptions$instance {
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Binary: Nullable_1<System_Internal.Boolean>;
    readonly Messages: Nullable_1<System_Internal.Boolean>;
    readonly ProtocolVersion: PgOutputProtocolVersion;
    readonly PublicationNames: List_1<System_Internal.String>;
    readonly StreamingMode: Nullable_1<PgOutputStreamingMode>;
    readonly TwoPhase: Nullable_1<System_Internal.Boolean>;
    Equals(other: PgOutputReplicationOptions): boolean;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
}


export const PgOutputReplicationOptions: {
    new(publicationName: string, protocolVersion: ulong, binary: Nullable_1<System_Internal.Boolean>, streaming: Nullable_1<System_Internal.Boolean>, messages: Nullable_1<System_Internal.Boolean>, twoPhase: Nullable_1<System_Internal.Boolean>): PgOutputReplicationOptions;
    new(publicationName: string, protocolVersion: PgOutputProtocolVersion, binary: Nullable_1<System_Internal.Boolean>, streamingMode: Nullable_1<PgOutputStreamingMode>, messages: Nullable_1<System_Internal.Boolean>, twoPhase: Nullable_1<System_Internal.Boolean>): PgOutputReplicationOptions;
    new(publicationNames: IEnumerable_1<System_Internal.String>, protocolVersion: ulong, binary: Nullable_1<System_Internal.Boolean>, streaming: Nullable_1<System_Internal.Boolean>, messages: Nullable_1<System_Internal.Boolean>, twoPhase: Nullable_1<System_Internal.Boolean>): PgOutputReplicationOptions;
    new(publicationNames: IEnumerable_1<System_Internal.String>, protocolVersion: PgOutputProtocolVersion, binary: Nullable_1<System_Internal.Boolean>, streamingMode: Nullable_1<PgOutputStreamingMode>, messages: Nullable_1<System_Internal.Boolean>, twoPhase: Nullable_1<System_Internal.Boolean>): PgOutputReplicationOptions;
};


export type PgOutputReplicationOptions = PgOutputReplicationOptions$instance;

export interface PgOutputReplicationSlot$instance extends LogicalReplicationSlot {
}


export const PgOutputReplicationSlot: {
    new(slotName: string): PgOutputReplicationSlot;
    new(options: ReplicationSlotOptions): PgOutputReplicationSlot;
};


export type PgOutputReplicationSlot = PgOutputReplicationSlot$instance;

export interface ReplicationTuple$instance {
    readonly __tsonic_iface_System_Collections_Generic_IAsyncEnumerable_1: never;

    NumColumns: ushort;
    GetAsyncEnumerator(cancellationToken?: CancellationToken): IAsyncEnumerator_1<ReplicationValue>;
}


export const ReplicationTuple: {
};


export type ReplicationTuple = ReplicationTuple$instance;

export interface ReplicationValue$instance {
    readonly IsDBNull: boolean;
    readonly IsUnchangedToastedValue: boolean;
    Kind: TupleDataKind;
    Length: int;
    Get<T>(cancellationToken?: CancellationToken): ValueTask_1<T>;
    Get(cancellationToken?: CancellationToken): ValueTask_1<unknown>;
    GetDataTypeName(): string;
    GetFieldName(): string;
    GetFieldType(): Type;
    GetPostgresType(): PostgresType;
    GetStream(): Stream;
    GetTextReader(): TextReader;
}


export const ReplicationValue: {
};


export type ReplicationValue = ReplicationValue$instance;

