// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Query.ExpressionTranslators.Internal
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { NpgsqlSqlExpressionFactory } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Query/internal/index.js";
import type { NpgsqlTypeMappingSource } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal/internal/index.js";
import type { IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { MemberInfo, MethodInfo } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Object as ClrObject, Type, Version } from "@tsonic/dotnet/System/internal/index.js";
import type { IDiagnosticsLogger_1 } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import type { IDbContextOptions } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IModel } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { SqlExpression } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.SqlExpressions/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Query_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query/internal/index.js";
import type { EnumerableExpression, IAggregateMethodCallTranslator, IAggregateMethodCallTranslatorProvider, IMemberTranslator, IMemberTranslatorProvider, IMethodCallTranslator, IMethodCallTranslatorProvider, ISqlExpressionFactory, RelationalAggregateMethodCallTranslatorProvider, RelationalAggregateMethodCallTranslatorProviderDependencies, RelationalMemberTranslatorProvider, RelationalMemberTranslatorProviderDependencies, RelationalMethodCallTranslatorProvider, RelationalMethodCallTranslatorProviderDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query/internal/index.js";
import type { IRelationalTypeMappingSource } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { DbLoggerCategory$Query } from "@tsonic/efcore/Microsoft.EntityFrameworkCore/internal/index.js";

export interface NpgsqlAggregateMethodCallTranslatorProvider$instance extends RelationalAggregateMethodCallTranslatorProvider {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IAggregateMethodCallTranslatorProvider: never;

}


export const NpgsqlAggregateMethodCallTranslatorProvider: {
    new(dependencies: RelationalAggregateMethodCallTranslatorProviderDependencies, model: IModel): NpgsqlAggregateMethodCallTranslatorProvider;
};


export type NpgsqlAggregateMethodCallTranslatorProvider = NpgsqlAggregateMethodCallTranslatorProvider$instance;

export interface NpgsqlArrayMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlArrayMethodTranslator: {
    new(sqlExpressionFactory: NpgsqlSqlExpressionFactory, jsonPocoTranslator: NpgsqlJsonPocoTranslator): NpgsqlArrayMethodTranslator;
};


export type NpgsqlArrayMethodTranslator = NpgsqlArrayMethodTranslator$instance;

export interface NpgsqlBigIntegerMemberTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslator: never;

    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlBigIntegerMemberTranslator: {
    new(sqlExpressionFactory: NpgsqlSqlExpressionFactory): NpgsqlBigIntegerMemberTranslator;
};


export type NpgsqlBigIntegerMemberTranslator = NpgsqlBigIntegerMemberTranslator$instance;

export interface NpgsqlByteArrayMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlByteArrayMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): NpgsqlByteArrayMethodTranslator;
};


export type NpgsqlByteArrayMethodTranslator = NpgsqlByteArrayMethodTranslator$instance;

export interface NpgsqlConvertTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlConvertTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): NpgsqlConvertTranslator;
};


export type NpgsqlConvertTranslator = NpgsqlConvertTranslator$instance;

export interface NpgsqlCubeTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslator: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlCubeTranslator: {
    new(sqlExpressionFactory: NpgsqlSqlExpressionFactory, typeMappingSource: IRelationalTypeMappingSource): NpgsqlCubeTranslator;
};


export type NpgsqlCubeTranslator = NpgsqlCubeTranslator$instance;

export interface NpgsqlDateTimeMemberTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslator: never;

    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlDateTimeMemberTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory): NpgsqlDateTimeMemberTranslator;
};


export type NpgsqlDateTimeMemberTranslator = NpgsqlDateTimeMemberTranslator$instance;

export interface NpgsqlDateTimeMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlDateTimeMethodTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory): NpgsqlDateTimeMethodTranslator;
};


export type NpgsqlDateTimeMethodTranslator = NpgsqlDateTimeMethodTranslator$instance;

export interface NpgsqlFullTextSearchMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlFullTextSearchMethodTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory, model: IModel): NpgsqlFullTextSearchMethodTranslator;
};


export type NpgsqlFullTextSearchMethodTranslator = NpgsqlFullTextSearchMethodTranslator$instance;

export interface NpgsqlFuzzyStringMatchMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlFuzzyStringMatchMethodTranslator: {
    new(sqlExpressionFactory: NpgsqlSqlExpressionFactory): NpgsqlFuzzyStringMatchMethodTranslator;
};


export type NpgsqlFuzzyStringMatchMethodTranslator = NpgsqlFuzzyStringMatchMethodTranslator$instance;

export interface NpgsqlGuidTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlGuidTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory, postgresVersion: Version): NpgsqlGuidTranslator;
};


export type NpgsqlGuidTranslator = NpgsqlGuidTranslator$instance;

export interface NpgsqlJsonDbFunctionsTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlJsonDbFunctionsTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory, model: IModel): NpgsqlJsonDbFunctionsTranslator;
};


export type NpgsqlJsonDbFunctionsTranslator = NpgsqlJsonDbFunctionsTranslator$instance;

export interface NpgsqlJsonDomTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslator: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlJsonDomTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory, model: IModel): NpgsqlJsonDomTranslator;
};


export type NpgsqlJsonDomTranslator = NpgsqlJsonDomTranslator$instance;

export interface NpgsqlJsonPocoTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslator: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
    TranslateArrayLength(expression: SqlExpression): SqlExpression | undefined;
    TranslateMemberAccess(instance: SqlExpression, member: SqlExpression, returnType: Type): SqlExpression | undefined;
}


export const NpgsqlJsonPocoTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory, model: IModel): NpgsqlJsonPocoTranslator;
};


export type NpgsqlJsonPocoTranslator = NpgsqlJsonPocoTranslator$instance;

export interface NpgsqlLikeTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlLikeTranslator: {
    new(sqlExpressionFactory: NpgsqlSqlExpressionFactory): NpgsqlLikeTranslator;
};


export type NpgsqlLikeTranslator = NpgsqlLikeTranslator$instance;

export interface NpgsqlLTreeTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslator: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlLTreeTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory, model: IModel): NpgsqlLTreeTranslator;
};


export type NpgsqlLTreeTranslator = NpgsqlLTreeTranslator$instance;

export interface NpgsqlMathTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlMathTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: ISqlExpressionFactory, model: IModel): NpgsqlMathTranslator;
};


export type NpgsqlMathTranslator = NpgsqlMathTranslator$instance;

export interface NpgsqlMemberTranslatorProvider$instance extends RelationalMemberTranslatorProvider {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslatorProvider: never;

    readonly JsonPocoTranslator: NpgsqlJsonPocoTranslator;
}


export const NpgsqlMemberTranslatorProvider: {
    new(dependencies: RelationalMemberTranslatorProviderDependencies, model: IModel, typeMappingSource: IRelationalTypeMappingSource, contextOptions: IDbContextOptions): NpgsqlMemberTranslatorProvider;
};


export type NpgsqlMemberTranslatorProvider = NpgsqlMemberTranslatorProvider$instance;

export interface NpgsqlMethodCallTranslatorProvider$instance extends RelationalMethodCallTranslatorProvider {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslatorProvider: never;

    readonly LTreeTranslator: NpgsqlLTreeTranslator;
}


export const NpgsqlMethodCallTranslatorProvider: {
    new(dependencies: RelationalMethodCallTranslatorProviderDependencies, model: IModel, contextOptions: IDbContextOptions): NpgsqlMethodCallTranslatorProvider;
};


export type NpgsqlMethodCallTranslatorProvider = NpgsqlMethodCallTranslatorProvider$instance;

export interface NpgsqlMiscAggregateMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IAggregateMethodCallTranslator: never;

    Translate(method: MethodInfo, source: EnumerableExpression, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlMiscAggregateMethodTranslator: {
    new(sqlExpressionFactory: NpgsqlSqlExpressionFactory, typeMappingSource: IRelationalTypeMappingSource, model: IModel): NpgsqlMiscAggregateMethodTranslator;
};


export type NpgsqlMiscAggregateMethodTranslator = NpgsqlMiscAggregateMethodTranslator$instance;

export interface NpgsqlNetworkTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlNetworkTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory, model: IModel): NpgsqlNetworkTranslator;
};


export type NpgsqlNetworkTranslator = NpgsqlNetworkTranslator$instance;

export interface NpgsqlObjectToStringTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlObjectToStringTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: ISqlExpressionFactory): NpgsqlObjectToStringTranslator;
};


export type NpgsqlObjectToStringTranslator = NpgsqlObjectToStringTranslator$instance;

export interface NpgsqlQueryableAggregateMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IAggregateMethodCallTranslator: never;

    Translate(method: MethodInfo, source: EnumerableExpression, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlQueryableAggregateMethodTranslator: {
    new(sqlExpressionFactory: NpgsqlSqlExpressionFactory, typeMappingSource: IRelationalTypeMappingSource): NpgsqlQueryableAggregateMethodTranslator;
};


export type NpgsqlQueryableAggregateMethodTranslator = NpgsqlQueryableAggregateMethodTranslator$instance;

export interface NpgsqlRandomTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlRandomTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): NpgsqlRandomTranslator;
};


export type NpgsqlRandomTranslator = NpgsqlRandomTranslator$instance;

export interface NpgsqlRangeTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslator: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlRangeTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, npgsqlSqlExpressionFactory: NpgsqlSqlExpressionFactory, model: IModel, supportsMultiranges: boolean): NpgsqlRangeTranslator;
};


export type NpgsqlRangeTranslator = NpgsqlRangeTranslator$instance;

export interface NpgsqlRegexTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlRegexTranslator: {
    new(typeMappingSource: NpgsqlTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory, supportRegexCount: boolean): NpgsqlRegexTranslator;
};


export type NpgsqlRegexTranslator = NpgsqlRegexTranslator$instance;

export interface NpgsqlRowValueTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlRowValueTranslator: {
    new(sqlExpressionFactory: NpgsqlSqlExpressionFactory): NpgsqlRowValueTranslator;
};


export type NpgsqlRowValueTranslator = NpgsqlRowValueTranslator$instance;

export interface NpgsqlStatisticsAggregateMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IAggregateMethodCallTranslator: never;

    Translate(method: MethodInfo, source: EnumerableExpression, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlStatisticsAggregateMethodTranslator: {
    new(sqlExpressionFactory: NpgsqlSqlExpressionFactory, typeMappingSource: IRelationalTypeMappingSource): NpgsqlStatisticsAggregateMethodTranslator;
};


export type NpgsqlStatisticsAggregateMethodTranslator = NpgsqlStatisticsAggregateMethodTranslator$instance;

export interface NpgsqlStringMemberTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslator: never;

    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlStringMemberTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): NpgsqlStringMemberTranslator;
};


export type NpgsqlStringMemberTranslator = NpgsqlStringMemberTranslator$instance;

export interface NpgsqlStringMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlStringMethodTranslator: {
    new(typeMappingSource: NpgsqlTypeMappingSource, sqlExpressionFactory: ISqlExpressionFactory): NpgsqlStringMethodTranslator;
};


export type NpgsqlStringMethodTranslator = NpgsqlStringMethodTranslator$instance;

export interface NpgsqlTimeSpanMemberTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMemberTranslator: never;

    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlTimeSpanMemberTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): NpgsqlTimeSpanMemberTranslator;
};


export type NpgsqlTimeSpanMemberTranslator = NpgsqlTimeSpanMemberTranslator$instance;

export interface NpgsqlTrigramsMethodTranslator$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Query_IMethodCallTranslator: never;

    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList_1<SqlExpression>, logger: IDiagnosticsLogger_1<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const NpgsqlTrigramsMethodTranslator: {
    new(typeMappingSource: IRelationalTypeMappingSource, sqlExpressionFactory: NpgsqlSqlExpressionFactory, model: IModel): NpgsqlTrigramsMethodTranslator;
};


export type NpgsqlTrigramsMethodTranslator = NpgsqlTrigramsMethodTranslator$instance;

