// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { StringBuilder } from "@tsonic/dotnet/System.Text.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";
import type { IDbContextOptions } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { ISqlGenerationHelper, RelationalDataReader } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";
import * as Microsoft_EntityFrameworkCore_Update_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Update.js";
import type { ColumnModificationParameters, IColumnModification, IModificationCommand, IModificationCommandBatchFactory, IModificationCommandFactory, INonTrackedModificationCommand, IReadOnlyModificationCommand, IUpdateSqlGenerator, ModificationCommand, ModificationCommandBatch, ModificationCommandBatchFactoryDependencies, ModificationCommandParameters, NonTrackedModificationCommandParameters, ReaderModificationCommandBatch, ResultSetMapping, UpdateSqlGenerator, UpdateSqlGeneratorDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Update.js";

export abstract class NpgsqlModificationCommand$protected {
    protected ProcessSinglePropertyJsonUpdate(parameters: ColumnModificationParameters): void;
}


export interface NpgsqlModificationCommand$instance extends NpgsqlModificationCommand$protected, ModificationCommand {
    PropagateResults(relationalReader: RelationalDataReader): void;
}


export const NpgsqlModificationCommand: {
    new(modificationCommandParameters: ModificationCommandParameters): NpgsqlModificationCommand;
    new(modificationCommandParameters: NonTrackedModificationCommandParameters): NpgsqlModificationCommand;
};


export type NpgsqlModificationCommand = NpgsqlModificationCommand$instance;

export abstract class NpgsqlModificationCommandBatch$protected {
    protected readonly MaxBatchSize: int;
    protected AddParameter(columnModification: IColumnModification): void;
    protected Consume(reader: RelationalDataReader): void;
    protected ConsumeAsync(reader: RelationalDataReader, cancellationToken?: CancellationToken): Task;
    protected ThrowAggregateUpdateConcurrencyException(reader: RelationalDataReader, commandIndex: int, expectedRowsAffected: int, rowsAffected: int): void;
    protected ThrowAggregateUpdateConcurrencyExceptionAsync(reader: RelationalDataReader, commandIndex: int, expectedRowsAffected: int, rowsAffected: int, cancellationToken: CancellationToken): Task;
}


export interface NpgsqlModificationCommandBatch$instance extends NpgsqlModificationCommandBatch$protected, ReaderModificationCommandBatch {
}


export const NpgsqlModificationCommandBatch: {
    new(dependencies: ModificationCommandBatchFactoryDependencies, maxBatchSize: int): NpgsqlModificationCommandBatch;
};


export type NpgsqlModificationCommandBatch = NpgsqlModificationCommandBatch$instance;

export interface NpgsqlModificationCommandBatchFactory$instance {
    Create(): ModificationCommandBatch;
}


export const NpgsqlModificationCommandBatchFactory: {
    new(dependencies: ModificationCommandBatchFactoryDependencies, options: IDbContextOptions): NpgsqlModificationCommandBatchFactory;
};


export type NpgsqlModificationCommandBatchFactory = NpgsqlModificationCommandBatchFactory$instance;

export interface NpgsqlModificationCommandFactory$instance {
    CreateModificationCommand(modificationCommandParameters: ModificationCommandParameters): IModificationCommand;
    CreateNonTrackedModificationCommand(modificationCommandParameters: NonTrackedModificationCommandParameters): INonTrackedModificationCommand;
}


export const NpgsqlModificationCommandFactory: {
    new(): NpgsqlModificationCommandFactory;
};


export type NpgsqlModificationCommandFactory = NpgsqlModificationCommandFactory$instance;

export abstract class NpgsqlUpdateSqlGenerator$protected {
    protected AppendInsertCommand(commandStringBuilder: StringBuilder, name: string, schema: string, writeOperations: IReadOnlyList<IColumnModification>, readOperations: IReadOnlyList<IColumnModification>, overridingSystemValue: boolean): void;
    protected AppendUpdateColumnValue(updateSqlGeneratorHelper: ISqlGenerationHelper, columnModification: IColumnModification, stringBuilder: StringBuilder, name: string, schema: string): void;
}


export interface NpgsqlUpdateSqlGenerator$instance extends NpgsqlUpdateSqlGenerator$protected, UpdateSqlGenerator {
    AppendDeleteOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
    AppendInsertOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
    AppendInsertOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, overridingSystemValue: boolean, requiresTransaction: boolean): ResultSetMapping;
    AppendObtainNextSequenceValueOperation(commandStringBuilder: StringBuilder, name: string, schema: string): void;
    AppendStoredProcedureCall(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
    AppendUpdateOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
}


export const NpgsqlUpdateSqlGenerator: {
    new(dependencies: UpdateSqlGeneratorDependencies): NpgsqlUpdateSqlGenerator;
};


export type NpgsqlUpdateSqlGenerator = NpgsqlUpdateSqlGenerator$instance;

