// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.DependencyInjection
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.Extensions.Caching.Memory, Microsoft.Extensions.DependencyInjection, Microsoft.Extensions.DependencyInjection.Abstractions, Microsoft.Extensions.Logging, Microsoft.Extensions.Options, Npgsql.EntityFrameworkCore.PostgreSQL

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { NpgsqlDbContextOptionsBuilder } from "../../Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System/internal/index.js";
import type { DbContext, DbContextOptionsBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore/internal/index.js";
import type { IServiceCollection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection/internal/index.js";

export abstract class NpgsqlServiceCollectionExtensions$instance {
    static AddEntityFrameworkNpgsql(serviceCollection: IServiceCollection): IServiceCollection;
    static AddNpgsql<TContext extends unknown & DbContext>(serviceCollection: IServiceCollection, connectionString: string | null, npgsqlOptionsAction?: Action_1<NpgsqlDbContextOptionsBuilder> | null, optionsAction?: Action_1<DbContextOptionsBuilder> | null): IServiceCollection;
}


export type NpgsqlServiceCollectionExtensions = NpgsqlServiceCollectionExtensions$instance;

