// Generated by tsbindgen - Architecture
// Namespace: Npgsql.EntityFrameworkCore.PostgreSQL.Infrastructure.Internal
// Assembly: Npgsql.EntityFrameworkCore.PostgreSQL

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { INpgsqlNameTranslator, NpgsqlDataSourceBuilder, ProvideClientCertificatesCallback, ProvidePasswordCallback } from "../../Npgsql/internal/index.js";
import type { IReadOnlyDictionary_2, IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { DbConnection, DbDataSource } from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import type { RemoteCertificateValidationCallback } from "@tsonic/dotnet/System.Net.Security/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Action_1, Boolean as ClrBoolean, IEquatable_1, Int32, Nullable_1, Object as ClrObject, String as ClrString, Type, Version, Void } from "@tsonic/dotnet/System/internal/index.js";
import type { IDiagnosticsLogger_1 } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { DbContextOptionsExtensionInfo, IDbContextOptions, IDbContextOptionsExtension, IModelValidator, ISingletonOptions, ModelValidatorDependencies, RelationalModelValidator, RelationalModelValidatorDependencies, RelationalOptionsExtension } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IEntityType, IKey, IModel, IProperty, StoreObjectIdentifier } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { DbLoggerCategory$Model$Validation, ParameterTranslationMode } from "@tsonic/efcore/Microsoft.EntityFrameworkCore/internal/index.js";
import type { IServiceCollection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection/internal/index.js";

export interface INpgsqlSingletonOptions$instance extends ISingletonOptions {
    readonly __tsonic_iface_Npgsql_EntityFrameworkCore_PostgreSQL_Infrastructure_Internal_INpgsqlSingletonOptions: never;

    readonly PostgresVersion: Version;
    readonly IsPostgresVersionSet: boolean;
    readonly UseRedshift: boolean;
    readonly ReverseNullOrderingEnabled: boolean;
    readonly EnumDefinitions: IReadOnlyList_1<EnumDefinition>;
    readonly UserRangeDefinitions: IReadOnlyList_1<UserRangeDefinition>;
}


export interface INpgsqlSingletonOptions$instance extends Microsoft_EntityFrameworkCore_Infrastructure_Internal.ISingletonOptions {}

export type INpgsqlSingletonOptions = INpgsqlSingletonOptions$instance;

export interface EnumDefinition$instance {
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly ClrType: Type;
    readonly Labels: IReadOnlyDictionary_2<unknown, System_Internal.String>;
    readonly NameTranslator: INpgsqlNameTranslator;
    readonly StoreTypeName: string;
    readonly StoreTypeSchema: string | undefined;
    Equals(obj: unknown): boolean;
    Equals(other: EnumDefinition): boolean;
    GetHashCode(): int;
}


export const EnumDefinition: {
    new(clrType: Type, name: string, schema: string, nameTranslator: INpgsqlNameTranslator): EnumDefinition;
};


export type EnumDefinition = EnumDefinition$instance;

export interface NpgsqlModelValidator$instance extends RelationalModelValidator {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IModelValidator: never;

    Validate(model: IModel, logger: IDiagnosticsLogger_1<DbLoggerCategory$Model$Validation>): void;
    ValidateCompatible(property: IProperty, duplicateProperty: IProperty, columnName: string, storeObject: StoreObjectIdentifier, logger: IDiagnosticsLogger_1<DbLoggerCategory$Model$Validation>): void;
    ValidateIdentityVersionCompatibility(model: IModel): void;
    ValidateIndexIncludeProperties(model: IModel): void;
    ValidateStoredProcedures(model: IModel, logger: IDiagnosticsLogger_1<DbLoggerCategory$Model$Validation>): void;
    ValidateTypeMappings(model: IModel, logger: IDiagnosticsLogger_1<DbLoggerCategory$Model$Validation>): void;
    ValidateValueGeneration(entityType: IEntityType, key: IKey, logger: IDiagnosticsLogger_1<DbLoggerCategory$Model$Validation>): void;
}


export const NpgsqlModelValidator: {
    new(dependencies: ModelValidatorDependencies, relationalDependencies: RelationalModelValidatorDependencies, npgsqlSingletonOptions: INpgsqlSingletonOptions): NpgsqlModelValidator;
};


export type NpgsqlModelValidator = NpgsqlModelValidator$instance;

export interface NpgsqlOptionsExtension$instance extends RelationalOptionsExtension {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IDbContextOptionsExtension: never;

    get AdminDatabase(): string | undefined;
    set AdminDatabase(value: string | undefined);
    get DataSource(): DbDataSource | undefined;
    set DataSource(value: DbDataSource | undefined);
    get DataSourceBuilderAction(): Action_1<NpgsqlDataSourceBuilder> | undefined;
    set DataSourceBuilderAction(value: Action_1<NpgsqlDataSourceBuilder> | undefined);
    readonly EnumDefinitions: IReadOnlyList_1<EnumDefinition>;
    readonly Info: DbContextOptionsExtensionInfo;
    readonly IsPostgresVersionSet: boolean;
    readonly MinBatchSize: Nullable_1<System_Internal.Int32>;
    readonly ParameterizedCollectionMode: ParameterTranslationMode;
    readonly PostgresVersion: Version;
    get ProvideClientCertificatesCallback(): ProvideClientCertificatesCallback | undefined;
    set ProvideClientCertificatesCallback(value: ProvideClientCertificatesCallback | undefined);
    get ProvidePasswordCallback(): ProvidePasswordCallback | undefined;
    set ProvidePasswordCallback(value: ProvidePasswordCallback | undefined);
    get RemoteCertificateValidationCallback(): RemoteCertificateValidationCallback | undefined;
    set RemoteCertificateValidationCallback(value: RemoteCertificateValidationCallback | undefined);
    ReverseNullOrdering: boolean;
    UseRedshift: boolean;
    readonly UserRangeDefinitions: IReadOnlyList_1<UserRangeDefinition>;
    ApplyServices(services: IServiceCollection): void;
    Clone(): RelationalOptionsExtension;
    Validate(options: IDbContextOptions): void;
    WithAdminDatabase(adminDatabase: string): NpgsqlOptionsExtension;
    WithConnection(connection: DbConnection): RelationalOptionsExtension;
    WithConnectionString(connectionString: string): RelationalOptionsExtension;
    WithDataSource(dataSource: DbDataSource): RelationalOptionsExtension;
    WithDataSourceConfiguration(dataSourceBuilderAction: Action_1<NpgsqlDataSourceBuilder>): NpgsqlOptionsExtension;
    WithEnumMapping(clrType: Type, enumName: string, schemaName: string, nameTranslator: INpgsqlNameTranslator): NpgsqlOptionsExtension;
    WithPostgresVersion(postgresVersion: Version): NpgsqlOptionsExtension;
    WithProvideClientCertificatesCallback(callback: ProvideClientCertificatesCallback): NpgsqlOptionsExtension;
    WithProvidePasswordCallback(callback: ProvidePasswordCallback): NpgsqlOptionsExtension;
    WithRedshift(useRedshift: boolean): NpgsqlOptionsExtension;
    WithRemoteCertificateValidationCallback(callback: RemoteCertificateValidationCallback): NpgsqlOptionsExtension;
    WithUseParameterizedCollectionMode(parameterizedCollectionMode: ParameterTranslationMode): RelationalOptionsExtension;
    WithUserRangeDefinition<TSubtype>(rangeName: string, schemaName?: string, subtypeName?: string): NpgsqlOptionsExtension;
    WithUserRangeDefinition(rangeName: string, schemaName: string, subtypeClrType: Type, subtypeName: string): NpgsqlOptionsExtension;
}


export const NpgsqlOptionsExtension: {
    new(): NpgsqlOptionsExtension;
    new(copyFrom: NpgsqlOptionsExtension): NpgsqlOptionsExtension;
    readonly DefaultPostgresVersion: Version;
};


export type NpgsqlOptionsExtension = NpgsqlOptionsExtension$instance;

export interface UserRangeDefinition$instance {
    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly StoreTypeName: string;
    readonly StoreTypeSchema: string | undefined;
    readonly SubtypeClrType: Type;
    readonly SubtypeName: string | undefined;
    _Clone_$(): UserRangeDefinition;
    Equals(obj: unknown): boolean;
    Equals(other: UserRangeDefinition): boolean;
    GetHashCode(): int;
    ToString(): string;
}


export const UserRangeDefinition: {
    new(name: string, schema: string, subtypeClrType: Type, subtypeName: string): UserRangeDefinition;
};


export type UserRangeDefinition = UserRangeDefinition$instance;

